// Phone Ad Maker: fifty themes, each a whole art direction the way an image ad is one:
// the ground, the palette, the faces and their treatment, the sign the words sit on,
// the number, the decorations, the accents and how they move, how the phones stand,
// the camera, the grade and the sound, and copy of its own in English and Spanish.
//
// Data only (catalog.js merges it; decor.js paints the new signs and grounds). A theme
// reaches the maker only once the owner approves it (THEME_REVIEW in catalog.js).
//
// The copy follows the house rules every line of the maker follows: nothing claims a
// person answers every message, urgency is only ever true (phones lose value; "text
// now" is an invitation), never a deadline, a countdown, a price about to move, a
// ranking or a promise about condition or speed the shop has not made.

const P = (ground, light, ink, accent, plate, plate_ink, more = {}) => ({ ground, light, ink, accent, plate, plate_ink, ...more });

export const THEME_PALETTES = {
  // signs & shops
  tag_kraft: P("#c9a36b", "#e6cc9c", "#1c1408", "#d62828", "#fff200", "#111111"),
  tag_white: P("#e9e6df", "#fbfaf6", "#141414", "#e4002b", "#ff9e1b", "#111111"),
  chalk_wood: P("#5b3a22", "#8a5a36", "#fffbea", "#ffd166", "#1f3a2e", "#fffbea"),
  pawn_black: P("#121110", "#3a332a", "#f4e3b5", "#d4a017", "#d4a017", "#121110"),
  hardware_yellow: P("#2b2b2b", "#5a5a5a", "#ffffff", "#ffc300", "#ffc300", "#111111"),
  laundry_mint: P("#bfe8dd", "#effaf6", "#0d3b36", "#ff6b6b", "#0d3b36", "#ffffff"),
  donut_pink: P("#ffc6d9", "#ffe6ef", "#4a2511", "#e8457a", "#4a2511", "#ffffff"),
  carwash_blue: P("#1e6fd9", "#7cc4ff", "#ffffff", "#ffe066", "#ffe066", "#0b2a5a"),
  taco_fiesta: P("#ff5a36", "#ffb347", "#ffffff", "#ffe066", "#1b998b", "#ffffff"),
  // retro & pop
  groovy_70s: P("#f2a541", "#f7d08a", "#3d1f0b", "#c8553d", "#3d1f0b", "#f7d08a"),
  arcade_80s: P("#120b2e", "#3b1f7a", "#ffffff", "#00f5d4", "#ff00a8", "#ffffff", { sky: ["#120b2e", "#3b1f7a", "#ff00a8", "#ffb3e6"], sil: "#07041a", sun: "#ffd166" }),
  y2k_holo: P("#c7d2fe", "#fde2ff", "#1a1446", "#7c3aed", "#1a1446", "#ffffff"),
  vapor_wave: P("#2d0b59", "#ff71ce", "#ffffff", "#01cdfe", "#b967ff", "#ffffff", { sky: ["#2d0b59", "#b967ff", "#ff71ce", "#fffb96"], sil: "#1a0636", sun: "#fffb96" }),
  pop_comic: P("#ffd60a", "#fff3a3", "#111111", "#e4002b", "#ffffff", "#111111"),
  diner_red: P("#d7263d", "#ff8fa3", "#ffffff", "#9ff2e9", "#f4f1de", "#d7263d"),
  mixtape_teal: P("#1b4b5a", "#3f8a9e", "#fff7e0", "#ffb703", "#fff7e0", "#1b4b5a"),
  disco_gold: P("#1a0f2e", "#5b2a86", "#fff4d6", "#f6c945", "#f6c945", "#1a0f2e"),
  // clean & premium
  studio_white: P("#eef0f3", "#ffffff", "#111318", "#0a84ff", "#111318", "#ffffff"),
  black_gold: P("#0c0c0d", "#2b2a28", "#f7f0dc", "#d4af37", "#d4af37", "#0c0c0d"),
  midnight_glass: P("#0b1636", "#28407a", "#ffffff", "#7dd3fc", "#7dd3fc", "#0b1636"),
  titanium_grey: P("#8d9097", "#d7d9dd", "#111214", "#c9a26b", "#111214", "#ffffff"),
  editorial_cream: P("#ecebe6", "#fbfaf7", "#16161a", "#c1121f", "#16161a", "#ffffff"),
  pastel_soft: P("#d8c7ff", "#fdf0ff", "#2b1d52", "#ff8fb1", "#2b1d52", "#ffffff"),
  swiss_mono: P("#f2f2f0", "#ffffff", "#0d0d0d", "#e10600", "#0d0d0d", "#ffffff"),
  aurora_glow: P("#101a33", "#3fd5c0", "#ffffff", "#b388ff", "#b388ff", "#101a33"),
  // night & neon
  cyber_night: P("#0a0f1f", "#1f3b73", "#e6f7ff", "#00f0ff", "#ff2bd6", "#ffffff"),
  radio_amber: P("#141012", "#3d2b24", "#ffe8c2", "#ffb000", "#ffb000", "#141012"),
  club_violet: P("#1c0930", "#6a1b9a", "#ffffff", "#ff4ecd", "#ff4ecd", "#ffffff"),
  rooftop_dusk: P("#2a2466", "#f7797d", "#ffffff", "#ffd166", "#b1447a", "#ffffff", { sky: ["#1b1740", "#2a2466", "#b1447a", "#f7797d"], sil: "#0f0c26", sun: "#ffb38a" }),
  prize_counter: P("#16122b", "#3b2f6b", "#ffffff", "#ffd60a", "#e4002b", "#ffffff"),
  noir_pink: P("#1a1216", "#4a2a3a", "#ffe3f1", "#ff5fa2", "#ff5fa2", "#1a1216"),
  // paper & print
  newsprint: P("#e9e5da", "#f7f4ec", "#171717", "#b3261e", "#171717", "#f7f4ec"),
  wanted_paper: P("#6b4a2b", "#a57a4d", "#fff4dd", "#e9c46a", "#e9d3a6", "#2b1a0e"),
  receipt_kraft: P("#b8905e", "#d9b88a", "#1a1a1a", "#d62828", "#fbfbf7", "#1a1a1a"),
  sticky_cork: P("#b98a5a", "#d9b38a", "#1b1b1b", "#d62828", "#ffe45c", "#1b1b1b"),
  blueprint_blue: P("#123f73", "#2d6cb3", "#ffffff", "#ffd166", "#ffffff", "#123f73"),
  kraft_box: P("#a47b4f", "#c9a172", "#1b1209", "#1f4e8c", "#f4ead8", "#1b1209"),
  postcard_sun: P("#ff8a5b", "#ffd6a5", "#ffffff", "#ffe066", "#fffdf6", "#1d3557", { sky: ["#3d1a70", "#b1447a", "#ff8a5b", "#ffd6a5"], sil: "#2a1238", sun: "#ffe7a0", sand: "#f2d7a6" }),
  notebook_blue: P("#f7f7f2", "#ffffff", "#1c2a6b", "#e63946", "#ffe45c", "#1c2a6b"),
  // street & sport
  gameday_navy: P("#0b1f3a", "#1f4e8c", "#ffffff", "#ffb703", "#ffb703", "#0b1f3a"),
  fight_poster: P("#d9c7a3", "#efe3c9", "#1a1a1a", "#b3261e", "#1a1a1a", "#efe3c9"),
  skate_concrete: P("#8d8f93", "#c5c7cb", "#111111", "#ff3e00", "#ffe600", "#111111"),
  market_green: P("#2f5d3a", "#6aa36f", "#fffbea", "#ffb703", "#1f3a2e", "#fffbea"),
  subway_tile: P("#e8ecea", "#ffffff", "#111111", "#ff2e88", "#00a86b", "#ffffff"),
  court_orange: P("#c86b2c", "#e8a66a", "#ffffff", "#111111", "#111111", "#ffffff"),
  // playful & bold
  candy_pop: P("#ff7ab8", "#ffd1e8", "#ffffff", "#fff05a", "#6a00f4", "#ffffff"),
  bubble_gum: P("#ffb3d9", "#ffe0f0", "#3a0d5c", "#ff006e", "#ffffff", "#3a0d5c"),
  rave_fluoro: P("#101010", "#2a2a2a", "#ffffff", "#ccff00", "#ff00e1", "#ffffff"),
  picnic_red: P("#f4efe6", "#ffffff", "#b3261e", "#1d6f42", "#b3261e", "#ffffff"),
  space_navy: P("#070b1f", "#243b8a", "#ffffff", "#ff9f1c", "#ff9f1c", "#070b1f"),
  money_green: P("#0f4d2e", "#2e8b57", "#f4f1de", "#d4af37", "#d4af37", "#0f4d2e"),
};

// The signs the new themes add (painted in decor.js themeBoard).
export const THEME_BOARDS = {
  price_tag: { ink: "#111111", accent: "#d62828", fx: ["flat", "hard_shadow"], pad: .42 },
  chalkboard: { ink: "#fffbea", accent: "#ffd166", fx: ["flat"], pad: .55, fonts: ["marker", "kalam", "cabin-sketch", "special-elite"] },
  receipt: { ink: "#1a1a1a", accent: "#d62828", fx: ["flat"], pad: .5, fonts: ["jetbrains", "special-elite", "roboto-slab", "oswald"] },
  wanted_poster: { ink: "#2b1a0e", accent: "#8b1e1e", fx: ["flat"], pad: .55, fonts: ["rye", "pirata", "special-elite", "roboto-slab", "zilla-slab"] },
  sticky_note: { ink: "#1b1b1b", accent: "#d62828", fx: ["flat"], pad: .45, fonts: ["marker", "kalam", "cabin-sketch"] },
  speech_bubble: { ink: "#111111", accent: "#e4002b", fx: ["flat", "hard_shadow"], pad: .45 },
  ticket_stub: { ink: "auto", fx: ["flat"], pad: .5 },
  led_panel: { ink: "#ffb000", accent: "#ff5a36", fx: ["glow", "flat"], pad: .5, fonts: ["press-start", "audiowide", "squada", "teko", "jetbrains"] },
  lightbox: { ink: "#111111", fx: ["flat", "shadow"], pad: .45 },
  postcard: { ink: "#1d3557", accent: "#e63946", fx: ["flat"], pad: .6, fonts: ["kaushan", "shrikhand", "young-serif", "knewave"] },
};

// The grounds the new themes add (painted in decor.js themeGround). Each is a material a
// theme paints in its own colours, so looks without a theme do not draw them.
export const THEME_GROUNDS = ["blueprint", "newsprint", "kraft", "wood", "tile", "brushed_metal", "carbon", "gingham",
  "starfield", "pegboard", "diamond_plate", "racing_stripes", "holo", "notebook"];

export const THEME_FAMILIES = ["Signs & shops", "Retro & pop", "Clean & premium", "Night & neon", "Paper & print", "Street & sport", "Playful & bold"];

const T = (family, label, spec) => ({ family, label, ...spec });

export const THEMES = {
  // ----------------------------------------------------------------- signs & shops
  price_tag: T("Signs & shops", "Price tag", { palettes: ["tag_kraft", "tag_white"], backgrounds: ["kraft", "tile", "concrete"],
    fonts: ["bungee", "oswald", "franklin", "big-shoulders"], boards: ["price_tag"], boardChance: 1, numbers: ["tag", "box", "plain"],
    accent_sets: ["cash", "money"], accent_kinds: ["asset", "mix"], phone_angles: ["angled", "flat"],
    style: { accent_in: ["swing", "drop", "pop"], urgency: ["none", "stamp", "arrows"], grade: ["clean", "warm"] },
    copy: { en: { headlines: ["CASH FOR YOUR IPHONE", "WHAT'S YOUR OLD IPHONE WORTH?", "PRICE CHECK: YOUR OLD IPHONE"], tags: ["TEXT A PIC, GET A PRICE", "FREE QUOTE", "ALL MODELS"], hooks: ["WHAT'S IT WORTH?"] },
      es: { headlines: ["¿CUÁNTO VALE TU IPHONE?", "EFECTIVO POR TU IPHONE"], tags: ["MÁNDANOS FOTO", "COTIZACIÓN GRATIS"] } } }),
  chalkboard_menu: T("Signs & shops", "Chalkboard menu", { palettes: ["chalk_wood"], backgrounds: ["wood"],
    fonts: ["marker", "kalam", "cabin-sketch"], boards: ["chalkboard"], boardChance: 1, numbers: ["underline", "plain"],
    accent_sets: ["sparkle", "checks"], accent_kinds: ["symbol"], phone_angles: ["flat", "angled"],
    style: { accent_in: ["fade", "pop"], text_in: ["wipe", "typewriter", "rise_mask"], grade: ["warm", "film"], sound_kit: ["lofi", "minimal"] },
    copy: { en: { headlines: ["ON THE MENU: CASH FOR IPHONES", "TODAY'S SPECIAL: YOUR OLD IPHONE", "WE BUY IPHONES"], tags: ["ASK FOR A QUOTE", "ALL MODELS", "LOCAL BUYER"] },
      es: { headlines: ["EN EL MENÚ: EFECTIVO POR IPHONES", "COMPRAMOS IPHONES"], tags: ["PIDE TU COTIZACIÓN"] } } }),
  pawn_gold: T("Signs & shops", "Pawn counter gold", { palettes: ["pawn_black", "black_gold"], backgrounds: ["carbon", "velvet", "brushed_metal"],
    fonts: ["rye", "zodiak", "gloock", "cormorant"], fx: ["gold", "foil", "chrome"], boards: ["lightbox", "none"], boardChance: .3, numbers: ["gold", "chrome", "box"],
    accent_sets: ["cash", "money"], accent_kinds: ["asset", "mix"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["flip3d", "zoom"], accent_idle: ["turntable", "float"], grade: ["warm", "punchy"], overlay: ["shimmer", "sparkle_field", "none"] },
    copy: { en: { headlines: ["CASH FOR IPHONES ON THE COUNTER", "YOUR OLD IPHONE IS WORTH CASH", "WE BUY IPHONES"], tags: ["ALL MODELS", "FREE QUOTE", "MEET LOCALLY"] },
      es: { headlines: ["TU IPHONE VIEJO VALE DINERO", "COMPRAMOS IPHONES"], tags: ["TODOS LOS MODELOS"] } } }),
  hardware_store: T("Signs & shops", "Hardware store", { palettes: ["hardware_yellow"], backgrounds: ["diamond_plate", "pegboard"],
    fonts: ["stencil", "oswald", "big-shoulders", "barlow-cond"], fx: ["flat", "hard_shadow", "box"], boards: ["store_sign", "price_tag"], boardChance: .6, numbers: ["box", "stacked", "plain"],
    accent_sets: ["checks", "deal"], accent_kinds: ["symbol", "asset"], phone_angles: ["flat", "angled"],
    style: { urgency: ["caution_tape", "arrows", "none"], accent_in: ["slide", "drop"], grade: ["punchy", "clean"], sound_kit: ["funk", "boombap"] },
    copy: { en: { headlines: ["WE BUY IPHONES. ANY MODEL.", "TRADE YOUR IPHONE FOR CASH", "CASH FOR IPHONES"], tags: ["ALL MODELS WANTED", "TEXT A PIC, GET A PRICE"] },
      es: { headlines: ["COMPRAMOS IPHONES", "CAMBIA TU IPHONE POR EFECTIVO"], tags: ["TODOS LOS MODELOS"] } } }),
  laundromat: T("Signs & shops", "Laundromat", { palettes: ["laundry_mint"], backgrounds: ["tile"],
    fonts: ["nunito", "sniglet", "satoshi", "bricolage"], fx: ["sticker", "box", "flat"], boards: ["lightbox", "none"], boardChance: .5, numbers: ["pill", "sticker"],
    accent_sets: ["sparkle", "trust"], accent_kinds: ["symbol", "mix"], phone_angles: ["turntable", "flat"],
    style: { accent_in: ["pop", "orbit"], accent_idle: ["float", "bob"], overlay: ["bokeh_drift", "none"], grade: ["clean"] },
    copy: { en: { headlines: ["FRESH CASH FOR OLD IPHONES", "CLEAN OUT THAT DRAWER", "WE BUY IPHONES"], tags: ["FREE QUOTE", "MEET LOCALLY"] },
      es: { headlines: ["EFECTIVO POR TU IPHONE VIEJO", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
  donut_shop: T("Signs & shops", "Donut shop", { palettes: ["donut_pink"], backgrounds: ["gingham", "tile"],
    fonts: ["shrikhand", "sniglet", "luckiest"], fx: ["sticker", "extrude", "hard_shadow"], boards: ["none", "sticky_note"], boardChance: .3, numbers: ["pill", "sticker"],
    accent_sets: ["sparkle", "hype"], accent_kinds: ["mix", "symbol"], phone_angles: ["angled", "wide_spin"],
    style: { accent_in: ["pop", "drop", "swing"], accent_idle: ["bob", "wiggle"], grade: ["warm", "clean"], sound_kit: ["funk", "house"] },
    copy: { en: { headlines: ["SWEET CASH FOR YOUR IPHONE", "SELL YOUR OLD IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "TEXT A PIC"] },
      es: { headlines: ["EFECTIVO POR TU IPHONE", "VENDE TU IPHONE"], tags: ["MÁNDANOS FOTO"] } } }),
  car_wash: T("Signs & shops", "Car wash", { palettes: ["carwash_blue"], backgrounds: ["bokeh", "waves", "rays"],
    fonts: ["bungee", "luckiest", "russo", "tilt-warp"], fx: ["sticker", "extrude", "double_outline"], boards: ["store_sign", "none"], boardChance: .4, numbers: ["pill", "sticker", "ticket"],
    accent_sets: ["sparkle"], accent_kinds: ["symbol"], phone_angles: ["wide_spin", "turntable"],
    style: { accent_in: ["zoom", "pop", "orbit"], accent_idle: ["pulse", "bob"], overlay: ["bokeh_drift", "shimmer"], grade: ["clean", "punchy"] },
    copy: { en: { headlines: ["SPARKLING CASH FOR OLD IPHONES", "WE BUY IPHONES", "SELL YOUR IPHONE"], tags: ["ALL MODELS", "FREE QUOTE", "LOCAL BUYER"] },
      es: { headlines: ["COMPRAMOS IPHONES", "VENDE TU IPHONE"], tags: ["TODOS LOS MODELOS"] } } }),
  taco_truck: T("Signs & shops", "Taco truck", { palettes: ["taco_fiesta"], backgrounds: ["racing_stripes", "tile", "stripes"],
    fonts: ["luckiest", "bungee", "kaushan", "knewave"], fx: ["sticker", "extrude", "hard_shadow"], boards: ["chalkboard", "store_sign", "none"], boardChance: .5, numbers: ["sticker", "tag", "pill"],
    accent_sets: ["local", "hype", "cash"], accent_kinds: ["mix"], phone_angles: ["angled", "flat"],
    style: { accent_in: ["drop", "pop", "fly"], accent_idle: ["wiggle", "bob"], sound_kit: ["afrobeat", "funk", "house"] },
    copy: { en: { headlines: ["WE BUY IPHONES, {AREA}", "CASH FOR YOUR IPHONE"], tags: ["SE HABLA ESPAÑOL", "LOCAL TO {AREA}"] },
      es: { headlines: ["¡COMPRAMOS IPHONES!", "¡EFECTIVO POR TU IPHONE!", "¡SE COMPRAN IPHONES!"], tags: ["¡MÁNDANOS FOTO!", "SOMOS DE {AREA}"] } } }),

  // ----------------------------------------------------------------- retro & pop
  groovy_70s: T("Retro & pop", "Groovy 70s", { palettes: ["groovy_70s"], backgrounds: ["racing_stripes", "mural_rainbow", "rays_corner"],
    fonts: ["shrikhand", "tilt-warp", "knewave"], fx: ["long_shadow", "extrude", "flat"], boards: ["none"], numbers: ["pill", "sticker"],
    accent_sets: ["sparkle", "hype"], accent_kinds: ["symbol"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["swing", "orbit"], accent_idle: ["wiggle", "float"], grade: ["film", "warm"], sound_kit: ["funk"], overlay: ["dust", "none"] },
    copy: { en: { headlines: ["GROOVY CASH FOR YOUR IPHONE", "FAR OUT: CASH FOR OLD IPHONES", "SELL YOUR IPHONE"], tags: ["FREE QUOTE", "LOCAL BUYER"] },
      es: { headlines: ["EFECTIVO POR TU IPHONE", "VENDE TU IPHONE"], tags: ["COTIZACIÓN GRATIS"] } } }),
  arcade_80s: T("Retro & pop", "Arcade 80s", { palettes: ["arcade_80s"], backgrounds: ["sunset_synth", "starfield", "grid"],
    fonts: ["press-start", "audiowide", "russo", "wallpoet"], fx: ["neon", "rgb_split", "glow"], boards: ["led_panel", "none"], boardChance: .5, numbers: ["neon", "outline", "box"],
    accent_sets: ["hype", "sparkle"], accent_kinds: ["symbol"], phone_angles: ["wide_spin", "angled"],
    style: { accent_in: ["zoom", "flip3d", "wide_spin"], accent_idle: ["pulse"], overlay: ["glitch", "grain_live"], sound_kit: ["edm", "trap"], grade: ["punchy"] },
    copy: { en: { headlines: ["INSERT IPHONE. GET CASH.", "PLAYER ONE: SELL YOUR IPHONE", "CASH FOR IPHONES"], tags: ["PRESS TEXT TO START", "ALL MODELS"], hooks: ["GAME OVER FOR YOUR OLD IPHONE?"] },
      es: { headlines: ["INSERTA IPHONE. RECIBE EFECTIVO.", "COMPRAMOS IPHONES"], tags: ["TODOS LOS MODELOS"] } } }),
  y2k_chrome: T("Retro & pop", "Y2K chrome", { palettes: ["y2k_holo", "pastel_soft"], backgrounds: ["holo", "mesh"],
    fonts: ["unbounded", "audiowide", "clash"], fx: ["chrome", "glass", "foil"], boards: ["none"], numbers: ["chrome", "pill"],
    accent_sets: ["sparkle"], accent_kinds: ["symbol"], phone_angles: ["wide_spin", "turntable"],
    style: { accent_in: ["wide_spin", "flip3d", "zoom"], accent_idle: ["turntable", "float"], overlay: ["shimmer", "sparkle_field"], sound_kit: ["house", "edm"] },
    copy: { en: { headlines: ["UPGRADED? CASH IN THE OLD ONE", "CASH FOR YOUR IPHONE", "SELL YOUR IPHONE"], tags: ["FREE QUOTE", "TEXT A PIC"] },
      es: { headlines: ["¿ESTRENASTE? VENDE EL VIEJO", "EFECTIVO POR TU IPHONE"], tags: ["COTIZACIÓN GRATIS"] } } }),
  vaporwave: T("Retro & pop", "Vaporwave", { palettes: ["vapor_wave"], backgrounds: ["sunset_synth", "sunset_ocean", "grid"],
    fonts: ["audiowide", "tilt-warp", "unbounded"], fx: ["gradient", "glow", "rgb_split"], boards: ["none"], decor: ["palms"], decorMin: 0, numbers: ["outline", "neon", "pill"],
    accent_sets: ["sparkle", "local"], accent_kinds: ["symbol", "mix"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["fade", "zoom"], accent_idle: ["float"], overlay: ["light_leak", "grain_live"], sound_kit: ["lofi"], grade: ["film"] },
    copy: { en: { headlines: ["C A S H  F O R  I P H O N E S", "SELL YOUR IPHONE", "WE BUY IPHONES"], tags: ["{AREA}", "FREE QUOTE"] },
      es: { headlines: ["COMPRAMOS IPHONES"], tags: ["{AREA}"] } } }),
  pop_comic: T("Retro & pop", "Pop art comic", { palettes: ["pop_comic"], backgrounds: ["halftone_comic", "halftone_duo", "rays_bold"],
    fonts: ["bangers", "luckiest", "bungee"], fx: ["sticker", "hard_shadow", "double_outline"], boards: ["speech_bubble", "none"], boardChance: .7, decor: ["starburst"], decorMin: 1, numbers: ["sticker", "box"],
    accent_sets: ["hype"], accent_kinds: ["symbol", "mix"], phone_angles: ["angled", "wide_spin"],
    style: { accent_in: ["pop", "zoom"], accent_idle: ["wiggle", "pulse"], text_in: ["slam", "stomp", "word_pop"], sound_kit: ["drumline", "funk"] },
    copy: { en: { headlines: ["POW! CASH FOR YOUR IPHONE", "WHAM! WE BUY IPHONES", "CASH FOR IPHONES!"], tags: ["TEXT A PIC!", "FREE QUOTE!"], burst: ["CASH!", "POW!"] },
      es: { headlines: ["¡PUM! EFECTIVO POR TU IPHONE", "¡COMPRAMOS IPHONES!"], tags: ["¡MÁNDANOS FOTO!"], burst: ["¡EFECTIVO!"] } } }),
  diner_50s: T("Retro & pop", "50s diner", { palettes: ["diner_red"], backgrounds: ["checker_floor", "checker", "tile"],
    fonts: ["kaushan", "shrikhand", "bungee"], fx: ["chrome", "sticker", "extrude"], boards: ["lightbox", "marquee", "none"], boardChance: .5, numbers: ["chrome", "pill"],
    accent_sets: ["sparkle", "cash"], accent_kinds: ["mix"], phone_angles: ["turntable", "flat"],
    style: { accent_in: ["flip3d", "pop"], accent_idle: ["turntable", "bob"], sound_kit: ["funk", "boombap"], grade: ["warm", "punchy"] },
    copy: { en: { headlines: ["ORDER UP: CASH FOR IPHONES", "WE BUY IPHONES", "SELL YOUR IPHONE"], tags: ["FREE QUOTE", "MEET LOCALLY"] },
      es: { headlines: ["COMPRAMOS IPHONES", "VENDE TU IPHONE"], tags: ["COTIZACIÓN GRATIS"] } } }),
  mixtape: T("Retro & pop", "Mixtape", { palettes: ["mixtape_teal"], backgrounds: ["kraft", "noise", "racing_stripes"],
    fonts: ["marker", "special-elite", "kalam"], fx: ["flat", "highlighter"], boards: ["sticky_note", "none"], boardChance: .5, numbers: ["underline", "plain"],
    accent_sets: ["sparkle", "checks"], accent_kinds: ["symbol"], phone_angles: ["flat", "angled"],
    style: { accent_in: ["slide", "swing"], accent_idle: ["still", "bob"], sound_kit: ["lofi", "boombap"], grade: ["film"], overlay: ["dust", "grain_live"] },
    copy: { en: { headlines: ["SIDE A: YOUR OLD IPHONE. SIDE B: CASH.", "SELL YOUR OLD IPHONE", "WE BUY IPHONES"], tags: ["TEXT A PIC", "LOCAL BUYER"] },
      es: { headlines: ["VENDE TU IPHONE VIEJO", "COMPRAMOS IPHONES"], tags: ["MÁNDANOS FOTO"] } } }),
  disco_night: T("Retro & pop", "Disco night", { palettes: ["disco_gold", "club_violet"], backgrounds: ["beams_cross", "bokeh", "beams_stage"],
    fonts: ["shrikhand", "tilt-warp", "unbounded"], fx: ["gold", "foil", "glow"], boards: ["none", "marquee"], boardChance: .3, numbers: ["gold", "pill"],
    accent_sets: ["sparkle"], accent_kinds: ["symbol"], phone_angles: ["turntable", "wide_spin"],
    style: { accent_in: ["orbit", "zoom"], accent_idle: ["pulse", "turntable"], overlay: ["sparkle_field", "light_rays"], sound_kit: ["house", "funk", "edm"] },
    copy: { en: { headlines: ["SHAKE OUT THAT OLD IPHONE", "CASH FOR YOUR IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "ALL MODELS"] },
      es: { headlines: ["EFECTIVO POR TU IPHONE", "COMPRAMOS IPHONES"], tags: ["TODOS LOS MODELOS"] } } }),

  // ----------------------------------------------------------------- clean & premium
  studio_white: T("Clean & premium", "Studio white", { palettes: ["studio_white", "editorial_cream"], backgrounds: ["radial", "tonal", "flat"],
    fonts: ["sora", "manrope", "instrument-sans", "satoshi"], fx: ["flat", "shadow"], boards: ["none"], numbers: ["plain", "pill"],
    accent_sets: ["checks", "trust"], accent_kinds: ["symbol"], phone_angles: ["angled", "turntable"],
    style: { accent_in: ["fade"], accent_idle: ["still"], text_in: ["rise_mask", "blur_in", "wipe"], overlay: ["none"], grade: ["clean"], camera: ["push_in", "still", "drift"], sound_kit: ["minimal", "lofi"] },
    copy: { en: { headlines: ["SELL YOUR IPHONE. SIMPLY.", "YOUR OLD IPHONE, SOLD.", "WE BUY IPHONES"], tags: ["FREE QUOTE", "MEET LOCALLY", "ALL MODELS"] },
      es: { headlines: ["VENDE TU IPHONE. ASÍ DE FÁCIL.", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
  black_gold: T("Clean & premium", "Black and gold", { palettes: ["black_gold"], backgrounds: ["carbon", "tonal", "velvet"],
    fonts: ["zodiak", "gloock", "cormorant", "young-serif"], fx: ["gold", "foil"], boards: ["none"], numbers: ["gold", "plain"],
    accent_sets: ["sparkle"], accent_kinds: ["symbol"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["fade", "flip3d"], accent_idle: ["turntable", "still"], overlay: ["shimmer", "none"], grade: ["warm", "matte"], camera: ["push_in", "drift"], sound_kit: ["minimal", "trap"] },
    copy: { en: { headlines: ["YOUR IPHONE IS WORTH MORE THAN A DRAWER", "CASH FOR YOUR IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "MEET LOCALLY"] },
      es: { headlines: ["TU IPHONE VALE MÁS QUE UN CAJÓN", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
  midnight_glass: T("Clean & premium", "Midnight glass", { palettes: ["midnight_glass"], backgrounds: ["drift", "aurora", "tonal"],
    fonts: ["clash", "satoshi", "sora"], fx: ["glass", "glow", "flat"], boards: ["none"], numbers: ["pill", "outline"],
    accent_sets: ["sparkle", "checks"], accent_kinds: ["symbol"], phone_angles: ["wide_spin", "turntable"],
    style: { accent_in: ["fade", "zoom"], accent_idle: ["float"], overlay: ["bloom", "none"], grade: ["cool", "clean"], sound_kit: ["minimal", "lofi", "edm"] },
    copy: { en: { headlines: ["UPGRADED? SELL THE OLD ONE", "CASH FOR YOUR IPHONE", "SELL YOUR IPHONE"], tags: ["FREE QUOTE", "TEXT A PIC"] },
      es: { headlines: ["¿ESTRENASTE? VENDE EL VIEJO", "VENDE TU IPHONE"], tags: ["MÁNDANOS FOTO"] } } }),
  titanium: T("Clean & premium", "Titanium", { palettes: ["titanium_grey"], backgrounds: ["brushed_metal"],
    fonts: ["sora", "unbounded", "manrope", "schibsted"], fx: ["flat", "chrome", "shadow"], boards: ["none"], numbers: ["plain", "chrome", "box"],
    accent_sets: ["checks"], accent_kinds: ["symbol"], phone_angles: ["angled", "turntable", "wide_spin"],
    style: { accent_in: ["slide", "fade"], accent_idle: ["still"], grade: ["cool", "clean"], sound_kit: ["minimal"] },
    copy: { en: { headlines: ["TITANIUM IN THE DRAWER? CASH IT IN.", "WE BUY IPHONES", "SELL YOUR IPHONE"], tags: ["ALL MODELS", "FREE QUOTE"] },
      es: { headlines: ["COMPRAMOS IPHONES", "VENDE TU IPHONE"], tags: ["TODOS LOS MODELOS"] } } }),
  editorial: T("Clean & premium", "Magazine cover", { palettes: ["editorial_cream", "studio_white"], backgrounds: ["flat", "noise", "newsprint"],
    fonts: ["gloock", "young-serif", "zodiak", "instrument-serif"], fx: ["flat"], boards: ["none"], numbers: ["plain", "underline"],
    accent_sets: ["checks"], accent_kinds: ["symbol"], phone_angles: ["angled", "flat"],
    style: { text_pos: ["top-left", "top-center"], accent_in: ["fade"], accent_idle: ["still"], text_in: ["rise_mask", "wipe"], grade: ["clean", "matte"], sound_kit: ["minimal", "lofi"] },
    copy: { en: { headlines: ["THE OLD IPHONE ISSUE", "YOUR OLD IPHONE, SOLD.", "WE BUY IPHONES"], tags: ["FREE QUOTE", "{AREA} LOCAL"] },
      es: { headlines: ["TU IPHONE VIEJO, VENDIDO.", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
  pastel_soft: T("Clean & premium", "Pastel soft", { palettes: ["pastel_soft", "y2k_holo"], backgrounds: ["mesh", "holo", "radial"],
    fonts: ["nunito", "sniglet", "bricolage"], fx: ["sticker", "flat", "shadow"], boards: ["none", "speech_bubble"], boardChance: .3, numbers: ["pill", "sticker"],
    accent_sets: ["sparkle", "deal"], accent_kinds: ["mix", "symbol"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["pop", "orbit", "fade"], accent_idle: ["float", "bob"], grade: ["clean"], sound_kit: ["lofi", "house"] },
    copy: { en: { headlines: ["SELL YOUR OLD IPHONE", "CASH FOR YOUR IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "TEXT A PIC"] },
      es: { headlines: ["VENDE TU IPHONE VIEJO", "EFECTIVO POR TU IPHONE"], tags: ["COTIZACIÓN GRATIS"] } } }),
  swiss_mono: T("Clean & premium", "Swiss mono", { palettes: ["swiss_mono"], backgrounds: ["grid", "flat"],
    fonts: ["schibsted", "franklin", "chivo", "instrument-sans"], fx: ["flat", "box"], boards: ["none"], numbers: ["box", "plain"],
    accent_sets: ["checks"], accent_kinds: ["symbol"], phone_angles: ["flat", "angled"],
    style: { text_pos: ["top-left", "middle-left"], color_mode: ["accent_word", "accent_line"], accent_in: ["slide"], accent_idle: ["still"], grade: ["clean"], sound_kit: ["minimal"] },
    copy: { en: { headlines: ["WE BUY IPHONES.", "IPHONE. CASH. LOCAL.", "SELL YOUR IPHONE."], tags: ["FREE QUOTE", "ALL MODELS"] },
      es: { headlines: ["COMPRAMOS IPHONES.", "IPHONE. EFECTIVO. LOCAL."], tags: ["COTIZACIÓN GRATIS"] } } }),
  aurora_glow: T("Clean & premium", "Aurora glow", { palettes: ["aurora_glow", "midnight_glass"], backgrounds: ["aurora", "drift"],
    fonts: ["clash", "satoshi", "unbounded"], fx: ["glow", "gradient", "flat"], boards: ["none"], numbers: ["pill", "neon"],
    accent_sets: ["sparkle"], accent_kinds: ["symbol"], phone_angles: ["turntable", "wide_spin"],
    style: { accent_in: ["fade", "orbit"], accent_idle: ["float", "pulse"], overlay: ["bloom", "none"], grade: ["cool"], sound_kit: ["lofi", "edm", "minimal"] },
    copy: { en: { headlines: ["CASH FOR YOUR IPHONE", "SELL YOUR IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "LOCAL BUYER"] },
      es: { headlines: ["EFECTIVO POR TU IPHONE", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),

  // ----------------------------------------------------------------- night & neon
  cyber_city: T("Night & neon", "Cyber city", { palettes: ["cyber_night"], backgrounds: ["carbon", "brick_neon_wash", "grid"],
    fonts: ["audiowide", "russo", "wallpoet", "squada"], fx: ["neon", "rgb_split", "glow"], boards: ["led_panel", "neon_box", "none"], boardChance: .5, numbers: ["neon", "outline"],
    accent_sets: ["hype", "phones"], accent_kinds: ["symbol"], phone_angles: ["wide_spin", "angled"],
    style: { accent_in: ["zoom", "flip3d", "slide"], accent_idle: ["pulse"], overlay: ["glitch", "grain_live"], grade: ["cool", "punchy"], sound_kit: ["trap", "edm"] },
    copy: { en: { headlines: ["UPLOAD YOUR OLD IPHONE. DOWNLOAD CASH.", "CASH FOR IPHONES", "WE BUY IPHONES"], tags: ["TEXT A PIC, GET A PRICE", "ALL MODELS"] },
      es: { headlines: ["COMPRAMOS IPHONES", "EFECTIVO POR TU IPHONE"], tags: ["MÁNDANOS FOTO"] } } }),
  late_radio: T("Night & neon", "Late-night radio", { palettes: ["radio_amber"], backgrounds: ["brick_lamp", "carbon", "tonal"],
    fonts: ["special-elite", "oswald", "teko", "squada"], fx: ["glow", "flat"], boards: ["led_panel", "none"], boardChance: .6, numbers: ["plain", "neon"],
    accent_sets: ["sparkle"], accent_kinds: ["symbol"], phone_angles: ["turntable", "flat"],
    style: { accent_in: ["fade"], accent_idle: ["pulse"], overlay: ["grain_live", "vignette_pulse"], grade: ["warm", "film"], sound_kit: ["lofi", "boombap"] },
    copy: { en: { headlines: ["NOW PLAYING: CASH FOR IPHONES", "WE BUY IPHONES", "SELL YOUR IPHONE"], tags: ["CALL OR TEXT", "LOCAL BUYER"] },
      es: { headlines: ["COMPRAMOS IPHONES", "VENDE TU IPHONE"], tags: ["LLAMA O MANDA TEXTO"] } } }),
  club_flyer: T("Night & neon", "Club flyer", { palettes: ["club_violet", "disco_gold"], backgrounds: ["beams_stage", "beams_cross", "bokeh"],
    fonts: ["unbounded", "bungee", "clash", "tilt-warp"], fx: ["foil", "gradient", "glow"], boards: ["none"], numbers: ["pill", "neon", "ticket"],
    accent_sets: ["hype", "sparkle"], accent_kinds: ["symbol", "mix"], phone_angles: ["wide_spin", "turntable"],
    style: { accent_in: ["zoom", "wide_spin"], accent_idle: ["pulse"], urgency: ["beat_pump", "flash_border", "none"], overlay: ["light_rays", "sparkle_field"], sound_kit: ["house", "edm", "afrobeat"] },
    copy: { en: { headlines: ["THE HEADLINER: YOUR OLD IPHONE", "CASH FOR IPHONES", "WE BUY IPHONES"], tags: ["FREE QUOTE", "{AREA}"] },
      es: { headlines: ["COMPRAMOS IPHONES", "EFECTIVO POR TU IPHONE"], tags: ["{AREA}"] } } }),
  rooftop_sunset: T("Night & neon", "Rooftop sunset", { palettes: ["rooftop_dusk"], backgrounds: ["sunset_dusk", "sunset_sky"],
    fonts: ["kaushan", "clash", "shrikhand"], fx: ["shadow", "sticker", "glow"], boards: ["none"], decor: ["palms", "skyline"], decorMax: 1, numbers: ["pill", "sticker"],
    accent_sets: ["local", "sparkle"], accent_kinds: ["mix"], phone_angles: ["angled", "turntable"],
    style: { accent_in: ["fade", "drop"], accent_idle: ["float"], grade: ["warm", "film"], overlay: ["light_leak", "none"], sound_kit: ["lofi", "house"] },
    copy: { en: { headlines: ["{AREA}, CASH FOR YOUR OLD IPHONE", "SELL YOUR IPHONE", "WE BUY IPHONES"], tags: ["FROM THE {CODE}", "LOCAL BUYER"] },
      es: { headlines: ["{AREA}, EFECTIVO POR TU IPHONE", "COMPRAMOS IPHONES"], tags: ["SOMOS DE {AREA}"] } } }),
  prize_counter: T("Night & neon", "Prize counter", { palettes: ["prize_counter"], backgrounds: ["starfield", "bokeh", "rays"],
    fonts: ["press-start", "bungee", "luckiest"], fx: ["sticker", "neon", "extrude"], boards: ["ticket_stub", "led_panel", "none"], boardChance: .6, numbers: ["ticket", "neon"],
    accent_sets: ["hype", "cash"], accent_kinds: ["mix", "symbol"], phone_angles: ["wide_spin", "angled"],
    style: { accent_in: ["pop", "fly", "orbit"], accent_idle: ["pulse", "wiggle"], overlay: ["confetti", "sparkle_field"], sound_kit: ["edm", "drumline"] },
    copy: { en: { headlines: ["TRADE IN YOUR IPHONE FOR CASH", "WE BUY IPHONES", "CASH FOR IPHONES"], tags: ["FREE QUOTE", "ALL MODELS"] },
      es: { headlines: ["CAMBIA TU IPHONE POR EFECTIVO", "COMPRAMOS IPHONES"], tags: ["TODOS LOS MODELOS"] } } }),
  noir_neon: T("Night & neon", "Noir neon", { palettes: ["noir_pink", "night_brick"], backgrounds: ["brick_lamp", "brick_wet"],
    fonts: ["kaushan", "melodrama", "shrikhand"], fx: ["neon", "glow"], boards: ["neon_box", "none"], boardChance: .5, decor: ["neon_arrow"], numbers: ["neon", "pill"],
    accent_sets: ["sparkle"], accent_kinds: ["symbol"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["fade", "flip3d"], accent_idle: ["pulse"], overlay: ["grain_live", "vignette_pulse"], grade: ["film", "cool"], sound_kit: ["trap", "lofi"] },
    copy: { en: { headlines: ["LIGHTS ON: CASH FOR IPHONES", "WE BUY IPHONES", "SELL YOUR IPHONE"], tags: ["TEXT US", "{AREA}"] },
      es: { headlines: ["COMPRAMOS IPHONES", "VENDE TU IPHONE"], tags: ["MÁNDANOS TEXTO"] } } }),

  // ----------------------------------------------------------------- paper & print
  classified_ad: T("Paper & print", "Classified ad", { palettes: ["newsprint"], backgrounds: ["newsprint"],
    fonts: ["roboto-slab", "zilla-slab", "special-elite", "franklin"], fx: ["flat", "box"], boards: ["none", "receipt"], boardChance: .3, numbers: ["box", "plain", "underline"],
    accent_sets: ["checks"], accent_kinds: ["symbol"], phone_angles: ["flat", "angled"],
    style: { text_in: ["typewriter", "wipe"], accent_in: ["fade"], accent_idle: ["still"], grade: ["matte", "film"], sound_kit: ["minimal", "boombap"] },
    copy: { en: { headlines: ["WANTED: IPHONES. CASH PAID.", "IPHONES WANTED", "WE BUY IPHONES"], tags: ["ALL MODELS", "CALL OR TEXT", "LOCAL BUYER"] },
      es: { headlines: ["SE BUSCAN IPHONES. PAGO EN EFECTIVO.", "COMPRAMOS IPHONES"], tags: ["LLAMA O MANDA TEXTO"] } } }),
  wanted_poster: T("Paper & print", "Wanted poster", { palettes: ["wanted_paper"], backgrounds: ["wood", "kraft"],
    fonts: ["rye", "pirata", "roboto-slab"], fx: ["flat"], boards: ["wanted_poster"], boardChance: 1, numbers: ["box", "plain"],
    accent_sets: ["cash", "money"], accent_kinds: ["asset", "mix"], phone_angles: ["angled", "flat"],
    style: { accent_in: ["swing", "drop"], accent_idle: ["wiggle", "still"], grade: ["film", "warm"], overlay: ["dust"], sound_kit: ["boombap", "drumline"] },
    copy: { en: { headlines: ["WANTED: YOUR OLD IPHONE", "WANTED: IPHONES", "IPHONES WANTED. CASH PAID."], tags: ["CASH PAID", "ALL MODELS", "TEXT A PIC"] },
      es: { headlines: ["SE BUSCA: TU IPHONE VIEJO", "SE BUSCAN IPHONES"], tags: ["PAGO EN EFECTIVO"] } } }),
  receipt: T("Paper & print", "Receipt", { palettes: ["receipt_kraft", "tag_white"], backgrounds: ["kraft", "tile", "concrete"],
    fonts: ["jetbrains", "special-elite", "oswald"], fx: ["flat"], boards: ["receipt"], boardChance: 1, numbers: ["plain", "underline", "box"],
    accent_sets: ["checks", "cash"], accent_kinds: ["symbol", "asset"], phone_angles: ["flat", "angled"],
    style: { text_in: ["typewriter", "wipe"], accent_in: ["slide", "pop"], accent_idle: ["still"], grade: ["clean", "matte"], sound_kit: ["minimal"] },
    copy: { en: { headlines: ["1 OLD IPHONE = CASH", "YOUR OLD IPHONE: PAID IN CASH", "WE BUY IPHONES"], tags: ["FREE QUOTE", "ALL MODELS"] },
      es: { headlines: ["1 IPHONE VIEJO = EFECTIVO", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
  sticky_note: T("Paper & print", "Sticky note", { palettes: ["sticky_cork", "notebook_blue"], backgrounds: ["cork", "wood", "notebook"],
    fonts: ["marker", "kalam", "cabin-sketch"], fx: ["flat"], boards: ["sticky_note"], boardChance: 1, numbers: ["underline", "plain"],
    accent_sets: ["checks", "sparkle"], accent_kinds: ["symbol"], phone_angles: ["flat", "angled"],
    style: { text_in: ["typewriter", "wipe"], accent_in: ["pop", "swing"], accent_idle: ["wiggle", "still"], grade: ["warm", "clean"], sound_kit: ["lofi"] },
    copy: { en: { headlines: ["NOTE TO SELF: SELL THE OLD IPHONE", "REMINDER: YOUR OLD IPHONE = CASH", "WE BUY IPHONES"], tags: ["TEXT A PIC", "FREE QUOTE"] },
      es: { headlines: ["NOTA: VENDE EL IPHONE VIEJO", "COMPRAMOS IPHONES"], tags: ["MÁNDANOS FOTO"] } } }),
  blueprint: T("Paper & print", "Blueprint", { palettes: ["blueprint_blue"], backgrounds: ["blueprint"],
    fonts: ["jetbrains", "barlow-cond", "saira-cond", "big-shoulders"], fx: ["flat", "outline"], boards: ["none"], numbers: ["outline", "box", "plain"],
    accent_sets: ["checks"], accent_kinds: ["symbol"], phone_angles: ["angled", "turntable"],
    style: { text_in: ["wipe", "typewriter"], accent_in: ["fade", "slide"], accent_idle: ["still"], grade: ["cool"], sound_kit: ["minimal", "lofi"] },
    copy: { en: { headlines: ["THE PLAN: OLD IPHONE TO CASH", "STEP 1: TEXT A PIC. STEP 2: CASH.", "WE BUY IPHONES"], tags: ["FREE QUOTE", "MEET LOCALLY"] },
      es: { headlines: ["EL PLAN: IPHONE VIEJO A EFECTIVO", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
  shipping_box: T("Paper & print", "Shipping box", { palettes: ["kraft_box"], backgrounds: ["kraft"],
    fonts: ["stencil", "special-elite", "big-shoulders"], fx: ["flat", "outline"], boards: ["price_tag", "none"], boardChance: .4, numbers: ["box", "stacked"],
    accent_sets: ["deal", "checks"], accent_kinds: ["asset", "symbol"], phone_angles: ["flat", "angled"],
    style: { accent_in: ["drop", "slide"], accent_idle: ["still"], urgency: ["stamp", "none", "arrows"], grade: ["warm"], sound_kit: ["boombap", "funk"] },
    copy: { en: { headlines: ["PACK UP THE OLD IPHONE. CASH IT IN.", "WE BUY IPHONES", "CASH FOR IPHONES"], tags: ["MEET LOCALLY", "ALL MODELS"] },
      es: { headlines: ["COMPRAMOS IPHONES", "EFECTIVO POR TU IPHONE"], tags: ["TODOS LOS MODELOS"] } } }),
  postcard: T("Paper & print", "Postcard", { palettes: ["postcard_sun"], backgrounds: ["beach_sunset", "sunset_ocean", "beach"],
    fonts: ["kaushan", "shrikhand", "young-serif"], fx: ["flat"], boards: ["postcard"], boardChance: 1, numbers: ["pill", "sticker"],
    accent_sets: ["local"], accent_kinds: ["mix", "asset"], phone_angles: ["angled", "turntable"],
    style: { accent_in: ["drop", "swing"], accent_idle: ["float"], grade: ["warm", "film"], sound_kit: ["lofi", "house"] },
    copy: { en: { headlines: ["GREETINGS FROM {AREA}: WE BUY IPHONES", "WISH YOU WERE CASHING IN YOUR IPHONE", "WE BUY IPHONES"], tags: ["FROM THE {CODE}", "LOCAL BUYER"] },
      es: { headlines: ["SALUDOS DESDE {AREA}: COMPRAMOS IPHONES", "COMPRAMOS IPHONES"], tags: ["SOMOS DE {AREA}"] } } }),
  notebook: T("Paper & print", "Notebook", { palettes: ["notebook_blue"], backgrounds: ["notebook"],
    fonts: ["kalam", "marker", "cabin-sketch"], fx: ["highlighter", "flat"], boards: ["none", "sticky_note"], boardChance: .3, numbers: ["underline", "plain"],
    accent_sets: ["checks", "sparkle"], accent_kinds: ["symbol"], phone_angles: ["flat", "angled"],
    style: { text_in: ["typewriter", "wipe"], accent_in: ["pop", "fade"], accent_idle: ["still", "wiggle"], grade: ["clean"], sound_kit: ["lofi", "minimal"] },
    copy: { en: { headlines: ["TO DO: SELL MY OLD IPHONE", "HOMEWORK: TURN YOUR OLD IPHONE INTO CASH", "WE BUY IPHONES"], tags: ["TEXT A PIC", "FREE QUOTE"] },
      es: { headlines: ["PENDIENTE: VENDER MI IPHONE VIEJO", "COMPRAMOS IPHONES"], tags: ["MÁNDANOS FOTO"] } } }),

  // ----------------------------------------------------------------- street & sport
  game_day: T("Street & sport", "Game day", { palettes: ["gameday_navy"], backgrounds: ["stripes", "carbon", "rays_bold"],
    fonts: ["big-shoulders", "teko", "saira-cond", "sofia-xcond"], fx: ["block3d", "extrude", "outline"], boards: ["none"], numbers: ["ticket", "box", "stacked"],
    accent_sets: ["hype", "deal"], accent_kinds: ["symbol", "mix"], phone_angles: ["angled", "wide_spin"],
    style: { text_in: ["slam", "stomp", "skew_slide"], accent_in: ["fly", "zoom"], accent_idle: ["pulse"], urgency: ["ticker", "flash_border", "none"], sound_kit: ["drumline", "trap"] },
    copy: { en: { headlines: ["SCORE CASH FOR YOUR IPHONE", "GAME DAY: WE BUY IPHONES", "CASH FOR IPHONES"], tags: ["ALL MODELS", "{AREA} LOCAL"] },
      es: { headlines: ["GANA EFECTIVO CON TU IPHONE", "COMPRAMOS IPHONES"], tags: ["TODOS LOS MODELOS"] } } }),
  fight_night: T("Street & sport", "Fight night poster", { palettes: ["fight_poster"], backgrounds: ["newsprint", "kraft", "noise"],
    fonts: ["big-shoulders", "rye", "oswald", "sofia-xcond"], fx: ["flat", "box", "hard_shadow"], boards: ["poster", "none"], boardChance: .4, numbers: ["box", "ticket"],
    accent_sets: ["hype"], accent_kinds: ["symbol"], phone_angles: ["angled", "flat"],
    style: { text_in: ["slam", "stomp"], accent_in: ["zoom", "pop"], accent_idle: ["still"], grade: ["film", "punchy"], overlay: ["dust", "grain_live"], sound_kit: ["drumline", "boombap"] },
    copy: { en: { headlines: ["YOUR IPHONE VS. THE DRAWER", "MAIN EVENT: CASH FOR IPHONES", "WE BUY IPHONES"], tags: ["ALL MODELS", "LOCAL BUYER"] },
      es: { headlines: ["TU IPHONE VS. EL CAJÓN", "COMPRAMOS IPHONES"], tags: ["TODOS LOS MODELOS"] } } }),
  skate_park: T("Street & sport", "Skate park", { palettes: ["skate_concrete", "spray_concrete"], backgrounds: ["concrete", "asphalt"],
    fonts: ["sedgwick", "wet-paint", "marker", "knewave"], fx: ["flat", "glow", "double_outline"], boards: ["none", "sticky_note"], boardChance: .2, decor: ["spray_halo"], decorMin: 0, numbers: ["sticker", "plain"],
    accent_sets: ["hype", "sparkle"], accent_kinds: ["symbol"], phone_angles: ["angled", "wide_spin"],
    style: { accent_in: ["fly", "slide", "drop"], accent_idle: ["wiggle"], camera: ["handheld", "whip_in"], sound_kit: ["boombap", "trap"] },
    copy: { en: { headlines: ["DROP IN: CASH FOR IPHONES", "WE BUY IPHONES", "SELL YOUR IPHONE"], tags: ["FROM THE {CODE}", "LOCAL BUYER"] },
      es: { headlines: ["COMPRAMOS IPHONES", "VENDE TU IPHONE"], tags: ["SOMOS DE AQUÍ"] } } }),
  street_market: T("Street & sport", "Farmers market", { palettes: ["market_green", "chalk_wood"], backgrounds: ["wood", "kraft"],
    fonts: ["kalam", "cabin-sketch", "marker", "young-serif"], fx: ["flat"], boards: ["chalkboard", "price_tag"], boardChance: .8, numbers: ["tag", "underline"],
    accent_sets: ["local", "checks"], accent_kinds: ["mix", "symbol"], phone_angles: ["flat", "angled"],
    style: { accent_in: ["drop", "swing"], accent_idle: ["bob"], grade: ["warm"], sound_kit: ["lofi", "afrobeat"] },
    copy: { en: { headlines: ["FRESH CASH FOR OLD IPHONES", "LOCAL BUYER: WE BUY IPHONES", "WE BUY IPHONES"], tags: ["{AREA} LOCAL", "MEET LOCALLY"] },
      es: { headlines: ["EFECTIVO POR IPHONES VIEJOS", "COMPRAMOS IPHONES"], tags: ["SOMOS DE {AREA}"] } } }),
  subway_graffiti: T("Street & sport", "Subway graffiti", { palettes: ["subway_tile"], backgrounds: ["tile"],
    fonts: ["sedgwick", "wet-paint", "marker", "bungee"], fx: ["double_outline", "flat", "sticker"], boards: ["none"], decor: ["spray_halo"], decorMin: 0, numbers: ["sticker", "tag"],
    accent_sets: ["hype", "phones"], accent_kinds: ["symbol"], phone_angles: ["angled", "flat"],
    style: { accent_in: ["slide", "zoom"], accent_idle: ["wiggle", "still"], camera: ["handheld", "drift"], sound_kit: ["boombap", "trap"] },
    copy: { en: { headlines: ["NEXT STOP: CASH FOR YOUR IPHONE", "WE BUY IPHONES", "CASH FOR IPHONES"], tags: ["{AREA} LOCAL", "TEXT A PIC"] },
      es: { headlines: ["PRÓXIMA PARADA: EFECTIVO POR TU IPHONE", "COMPRAMOS IPHONES"], tags: ["MÁNDANOS FOTO"] } } }),
  court_side: T("Street & sport", "Court side", { palettes: ["court_orange"], backgrounds: ["wood"],
    fonts: ["big-shoulders", "teko", "bungee", "sofia-xcond"], fx: ["block3d", "hard_shadow", "outline"], boards: ["none"], numbers: ["box", "stacked"],
    accent_sets: ["hype", "deal"], accent_kinds: ["symbol", "asset"], phone_angles: ["wide_spin", "angled"],
    style: { text_in: ["slam", "skew_slide"], accent_in: ["drop", "fly"], accent_idle: ["bob"], sound_kit: ["drumline", "trap"] },
    copy: { en: { headlines: ["NOTHING BUT CASH FOR YOUR IPHONE", "WE BUY IPHONES", "SCORE CASH FOR YOUR IPHONE"], tags: ["ALL MODELS", "{AREA} LOCAL"] },
      es: { headlines: ["COMPRAMOS IPHONES", "GANA EFECTIVO CON TU IPHONE"], tags: ["TODOS LOS MODELOS"] } } }),

  // ----------------------------------------------------------------- playful & bold
  candy_pop: T("Playful & bold", "Candy pop", { palettes: ["candy_pop", "bubble_gum"], backgrounds: ["candy_fade", "gingham", "confetti"],
    fonts: ["sniglet", "luckiest", "shrikhand"], fx: ["sticker", "extrude"], boards: ["none", "speech_bubble"], boardChance: .3, numbers: ["sticker", "pill"],
    accent_sets: ["sparkle", "hype"], accent_kinds: ["symbol", "mix"], phone_angles: ["wide_spin", "turntable"],
    style: { accent_in: ["pop", "orbit", "wide_spin"], accent_idle: ["bob", "wiggle"], overlay: ["confetti", "sparkle_field"], sound_kit: ["house", "funk"] },
    copy: { en: { headlines: ["SWEET CASH FOR YOUR OLD IPHONE", "SELL YOUR IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "TEXT A PIC"] },
      es: { headlines: ["EFECTIVO POR TU IPHONE VIEJO", "VENDE TU IPHONE"], tags: ["COTIZACIÓN GRATIS"] } } }),
  bubble_gum: T("Playful & bold", "Bubble gum", { palettes: ["bubble_gum"], backgrounds: ["gingham", "radial", "bokeh"],
    fonts: ["nunito", "sniglet", "luckiest"], fx: ["sticker", "flat"], boards: ["speech_bubble"], boardChance: .8, numbers: ["pill", "sticker"],
    accent_sets: ["sparkle", "deal"], accent_kinds: ["mix", "symbol"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["pop", "zoom"], accent_idle: ["pulse", "bob"], sound_kit: ["house", "funk"] },
    copy: { en: { headlines: ["POP! CASH FOR YOUR IPHONE", "SELL YOUR OLD IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "TEXT A PIC"] },
      es: { headlines: ["¡EFECTIVO POR TU IPHONE!", "VENDE TU IPHONE VIEJO"], tags: ["MÁNDANOS FOTO"] } } }),
  highlighter_rave: T("Playful & bold", "Highlighter rave", { palettes: ["rave_fluoro"], backgrounds: ["carbon", "fluoro", "grid"],
    fonts: ["bangers", "unbounded", "bungee"], fx: ["highlighter", "glow"], boards: ["none"], numbers: ["neon", "box"],
    accent_sets: ["hype"], accent_kinds: ["symbol"], phone_angles: ["wide_spin", "turntable"],
    style: { accent_in: ["zoom", "wide_spin", "fly"], accent_idle: ["pulse"], urgency: ["beat_pump", "flash_border"], overlay: ["glitch", "confetti"], sound_kit: ["edm", "trap"] },
    copy: { en: { headlines: ["CASH FOR IPHONES", "SELL YOUR IPHONE", "WE BUY IPHONES"], tags: ["ALL MODELS", "TEXT A PIC"] },
      es: { headlines: ["COMPRAMOS IPHONES", "VENDE TU IPHONE"], tags: ["TODOS LOS MODELOS"] } } }),
  picnic: T("Playful & bold", "Picnic check", { palettes: ["picnic_red"], backgrounds: ["gingham"],
    fonts: ["kaushan", "young-serif", "shrikhand"], fx: ["flat", "sticker"], boards: ["sticky_note", "none"], boardChance: .4, numbers: ["pill", "underline"],
    accent_sets: ["sparkle", "local"], accent_kinds: ["symbol", "mix"], phone_angles: ["angled", "flat"],
    style: { accent_in: ["drop", "swing"], accent_idle: ["bob"], grade: ["warm", "clean"], sound_kit: ["lofi", "afrobeat"] },
    copy: { en: { headlines: ["EASY CASH FOR YOUR OLD IPHONE", "WE BUY IPHONES", "SELL YOUR IPHONE"], tags: ["MEET LOCALLY", "FREE QUOTE"] },
      es: { headlines: ["EFECTIVO POR TU IPHONE VIEJO", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
  space_launch: T("Playful & bold", "Space launch", { palettes: ["space_navy", "arcade_80s"], backgrounds: ["starfield"],
    fonts: ["audiowide", "russo", "unbounded", "saira-cond"], fx: ["glow", "chrome", "extrude"], boards: ["none", "led_panel"], boardChance: .3, numbers: ["pill", "outline"],
    accent_sets: ["sparkle", "hype"], accent_kinds: ["symbol"], phone_angles: ["wide_spin", "turntable"],
    style: { accent_in: ["fly", "orbit", "zoom"], accent_idle: ["float"], entry: ["zoom", "spiral_in", "orbit"], sound_kit: ["edm", "minimal"] },
    copy: { en: { headlines: ["LAUNCH YOUR OLD IPHONE INTO CASH", "WE BUY IPHONES", "CASH FOR IPHONES"], tags: ["FREE QUOTE", "ALL MODELS"] },
      es: { headlines: ["COMPRAMOS IPHONES", "EFECTIVO POR TU IPHONE"], tags: ["TODOS LOS MODELOS"] } } }),
  money_green: T("Playful & bold", "Money green", { palettes: ["money_green"], backgrounds: ["checker_diamond", "carbon", "rays_bold"],
    fonts: ["cormorant", "rye", "zodiak", "big-shoulders"], fx: ["gold", "foil", "extrude"], boards: ["none"], numbers: ["gold", "box"],
    accent_sets: ["cash", "money"], accent_kinds: ["asset", "mix"], phone_angles: ["turntable", "angled"],
    style: { accent_in: ["flip3d", "drop", "fly"], accent_idle: ["turntable", "float"], overlay: ["shimmer", "none"], sound_kit: ["trap", "funk"] },
    copy: { en: { headlines: ["TURN YOUR OLD IPHONE INTO CASH", "CASH FOR YOUR IPHONE", "WE BUY IPHONES"], tags: ["FREE QUOTE", "ALL MODELS"] },
      es: { headlines: ["CONVIERTE TU IPHONE EN EFECTIVO", "COMPRAMOS IPHONES"], tags: ["COTIZACIÓN GRATIS"] } } }),
};
