/* generated by scripts/ingest_assets.py from assets/offer-assets.json; do not edit by hand.
   Owner-sourced pictures and grounds for the offer family (offer-library.js reads this at load). */
window.OFFER_ASSETS = {"size": {}, "sets": {}, "replaces": {}, "grounds": {}};
