#!/usr/bin/env python3
"""REAL VEHICLES (AND DEVICES, GOLD, SILVER AND COINS), CUT FROM COMMONS PHOTOGRAPHS.

The owner, 2026-10-02, on the car backdrops: "more popular cars and less
bikes", "some trucks and work vans", "semis". The car cut-outs in
assets/cutouts until now were renders of no real model (a sedan with a made-up
badge, a pickup and a van with none). assets/bg-web already holds Wikimedia
Commons photographs of real ones, freely licensed and credited in
assets/bg-web/ATTRIBUTION.json (scripts/fetch_backdrops.mjs). This cuts the
vehicle out of each one named in SPEC:

  - the vehicle is segmented (rembg, BiRefNet) and only it is kept:
    the biggest part of the mask, plus anything touching it that is big;
  - below `floor` (the tyres' contact line) nothing is kept, so no grass or
    pavement comes with it;
  - the edge is cleaned of the old background's colour (unmixed against the
    background around it, as scripts/ingest_assets.py does for a flat one);
  - each licence plate (and its dealer frame) in `plates` is blurred past
    reading; boxes set by eye on the 1920px photograph;
  - checked as ingest_assets.check_cutout checks a packshot: whole (not cut
    off by the frame, DESIGN-LAW 79), and big enough.

Landed in assets/cutouts/<id>.webp and credited in
assets/cutouts/ATTRIBUTION.json (licence, artist, Commons page) like
poke-psa-charizard. Not added to assets/approved-assets.json: that is the
owner's own pass.

Chosen by eye, 2026-10-02: left out are the brown F-150 and the 1977
Silverado (people in the cab), the 1956 Chevy (a classic, not a popular car),
the F-250 (a flag on a pole in the bed) and the Transit Courier at the show
(doors open, people round it). 2026-10-03: cut and then dropped, a 1969
Charger (driver at the wheel), a Silverado HD (arm out of the window) and an
Escalade (price sticker on the windscreen, the photographer in the paint);
then an Urus Performante (cut off at the frame), a Rivian R2 and a 2026 Land
Cruiser (people in the cab), a 911 GT3 RS (another car fused to it), a TRX (a
store security cable) and, of the Apple photographs, two iPhone 17 Pro Max
(store cradle left on), two Mac minis and three MacBook Airs (cables); a
Cybertruck at night (orange cast) and a 2026 RAV4 (display stand under it).
2026-10-04, of the popular2 photographs: left out a Macan (charging cable in), an
ID.4 (a road sign over the bonnet), an XC90 (another car fused to its nose) and
any with people in or round the car, a hand, a crowd or a cropped bumper; of the
other categories, every photograph with a hand, a wrist, a shop stand or a
price label, and every card and Pokemon photograph but one graded slab (the
rest were business cards, vending machines and players at tables).

  python3 scripts/cut_vehicle_photos.py            dry run: .render/vehicles/_review.jpg
  python3 scripts/cut_vehicle_photos.py --write    land them
  ONLY='^photo-gold' python3 scripts/cut_vehicle_photos.py   only the ids that match

needs: pip install pillow numpy opencv-python-headless "rembg[cpu]"
       (the model, about 1 GB, is fetched from github.com/danielgatis/rembg on first use)
"""
import json, os, re, sys
import numpy as np
import cv2
from PIL import Image, ImageDraw, ImageFilter

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
from ingest_assets import check_cutout   # noqa: E402

WEB = os.path.join(ROOT, 'assets', 'bg-web')
CUT = os.path.join(ROOT, 'assets', 'cutouts')
REVIEW = os.path.join(ROOT, '.render', 'vehicles')
WRITE = '--write' in sys.argv

# id: source photograph, what it is, plates [x0, y0, x1, y1], floor (y below
# which nothing is kept; None keeps the mask as it is)
SPEC = {
    'car-ford-f150-black': dict(src='trucks-ford-f-150-3.jpg', floor=None, plates=[],
        subject='a black Ford F-150 (fourteenth generation, 2021-), SuperCrew pickup, rear three-quarter'),
    'car-chevy-silverado-red': dict(src='trucks-chevrolet-silverado-pickup-1.jpg', floor=None, plates=[[1488, 968, 1598, 1072]],
        subject='a red Chevrolet C10 Silverado pickup (1981-87 square body), front three-quarter'),
    'car-ford-transit-connect-white': dict(src='vans-ford-transit-van-2.jpg', floor=None, plates=[[186, 836, 462, 940]],
        subject='a white Ford Transit Connect work van (third generation), front three-quarter'),
    'car-ford-transit-courier-white': dict(src='vans-ford-transit-van-3.jpg', floor=None, plates=[[1282, 818, 1558, 942]],
        subject='a white Ford Transit Courier work van (second generation), rear three-quarter'),
    'car-ldv-maxus-van-white': dict(src='vans-cargo-van-1.jpg', floor=None, plates=[],
        subject='a white LDV Maxus panel van, front three-quarter (its plate is already blank in the photograph)'),
    'car-harley-softail-black': dict(src='bikes-harley-davidson-motorcycle-1.jpg', floor=None, plates=[],
        subject='a black Harley-Davidson Softail Springer motorcycle, side on'),
    # 2026-10-03, from the popular / trucks / vans / semis fetch
    'car-toyota-camry-silver': dict(src='popular-toyota-camry-5.jpg', floor=None, plates=[[1598, 524, 1745, 616]],
        subject='a silver Toyota Camry (XV70, 2018-) sedan, front three-quarter'),
    'car-toyota-corolla-white': dict(src='popular-toyota-corolla-3.jpg', floor=None, plates=[[272, 450, 438, 530]],
        subject='a white Toyota Corolla (E170, 2014-19) sedan, rear three-quarter'),
    'car-honda-civic-white': dict(src='popular-honda-civic-6.jpg', floor=None, plates=[[1382, 744, 1684, 854]],
        subject='a white Honda Civic (eleventh generation, 2022-) hatchback, front three-quarter'),
    'car-honda-civic-type-r-blue': dict(src='popular-honda-civic-type-r-2.jpg', floor=None, plates=[[1492, 670, 1672, 760]],
        subject='a blue Honda Civic Type R (FK8, 2017-21), front three-quarter'),
    'car-honda-crv-silver': dict(src='popular-honda-cr-v-1.jpg', floor=None, plates=[],
        subject='a silver Honda CR-V (fifth generation, 2017-22) in a showroom, front three-quarter, no plate'),
    'car-toyota-rav4-white': dict(src='popular-toyota-rav4-2.jpg', floor=None, plates=[],
        subject='a white Toyota RAV4 Hybrid (XA50, 2019-) with a black roof, front three-quarter, show plate only'),
    'car-toyota-4runner-green': dict(src='popular-toyota-4runner-4.jpg', floor=None, plates=[],
        subject='an Army Green Toyota 4Runner TRD Pro (N280), front three-quarter, no plate'),
    'car-mercedes-g-class-orange': dict(src='popular-mercedes-benz-g-class-3.jpg', floor=None, plates=[[146, 822, 360, 920]],
        subject='a matte orange Mercedes-Benz G-Class (W463, 2018-) Professional Line, front three-quarter'),
    'car-bmw-m3-blue': dict(src='popular-bmw-m3-3.jpg', floor=None, plates=[[240, 744, 524, 844]],
        subject='a blue BMW M3 CS (F80) sedan, front three-quarter'),
    'car-lamborghini-urus-green': dict(src='popular-lamborghini-urus-2.jpg', floor=None, plates=[[210, 770, 470, 864]],
        subject='a green Lamborghini Urus SE (2024-), front three-quarter'),
    'car-bentley-bentayga-grey': dict(src='popular-bentley-bentayga-5.jpg', floor=None, plates=[[1566, 676, 1764, 766]],
        subject='a grey-blue Bentley Bentayga Azure (facelift, 2021-), front three-quarter'),
    'car-audi-s5-white': dict(src='popular-audi-s5-5.jpg', floor=None, plates=[[276, 446, 378, 522]],
        subject='a white Audi S5 Sportback (F5), front three-quarter'),
    'car-lexus-is-white': dict(src='popular-lexus-is-5.jpg', floor=None, plates=[[296, 716, 456, 832]],
        subject='a white Lexus IS 300 AWD (2021) sedan, front three-quarter'),
    'car-toyota-tacoma-orange': dict(src='trucks-toyota-tacoma-6.jpg', floor=None, plates=[[1524, 834, 1726, 938]],
        subject='an orange Toyota Tacoma TRD Off Road (N400, 2024-) double cab pickup, front three-quarter'),
    'car-ram-1500-blue': dict(src='trucks-ram-1500-3.jpg', floor=None, plates=[[1240, 962, 1474, 1044]],
        subject='a blue Ram 1500 crew cab pickup, front three-quarter'),
    'car-ram-promaster-grey': dict(src='vans-ram-promaster-4.jpg', floor=None, plates=[[1684, 836, 1784, 934]],
        subject='a grey 2014 Ram ProMaster 1500 Tradesman low-roof work van, front three-quarter'),
    'car-mercedes-sprinter-white': dict(src='vans-mercedes-benz-sprinter-2.jpg', floor=None, plates=[],
        subject='a white Mercedes-Benz Sprinter 4x4 tipper (chassis cab, 2023-) at a show, front three-quarter, show plate only'),
    'car-peterbilt-389-white': dict(src='semis-peterbilt-389-4.jpg', floor=None, plates=[[454, 1004, 580, 1080], [585, 1058, 636, 1104]],
        subject='a white Peterbilt 389 day-cab semi tractor, front three-quarter'),
    'car-freightliner-cascadia-blue': dict(src='semis-freightliner-cascadia-4.jpg', floor=None, plates=[],
        subject='a blue Freightliner Cascadia (second generation) sleeper semi tractor, front three-quarter, no front plate'),
    # 2026-10-03, round two ("MORE"): popular, top trims, Teslas, trucks, vans, semis
    'car-toyota-highlander-silver': dict(src='popular-toyota-highlander-3.jpg', floor=None, plates=[],
        subject='a silver Toyota Highlander (XU70, 2022), front three-quarter, no plate'),
    'car-tesla-model-3-white': dict(src='popular-tesla-model-3-4.jpg', floor=None, plates=[[270, 795, 630, 935]],
        subject='a white Tesla Model 3 (2023 Highland), front three-quarter'),
    'car-tesla-model-y-white': dict(src='popular-tesla-model-y-6.jpg', floor=None, plates=[],
        subject='a white Tesla Model Y (2025 Juniper) in a Tesla store, front three-quarter, no plate'),
    'car-jeep-wrangler-rubicon-lime': dict(src='popular-jeep-wrangler-2.jpg', floor=None, plates=[[190, 655, 392, 750], [1085, 640, 1365, 695]],
        subject='a lime Jeep Wrangler Rubicon 4xe (JL), front three-quarter; dealer lettering on the door blurred'),
    'car-nissan-rogue-copper': dict(src='popular-nissan-rogue-1.jpg', floor=None, plates=[],
        subject='a copper Nissan Rogue / X-Trail (T33), front three-quarter, no plate'),
    'car-chevy-tahoe-black': dict(src='popular-chevrolet-tahoe-4.jpg', floor=None, plates=[[1270, 920, 1550, 1022]],
        subject='a black Chevrolet Tahoe (2015-20), front three-quarter'),
    'car-ford-explorer-white': dict(src='popular-ford-explorer-3.jpg', floor=None, plates=[[190, 665, 405, 762]],
        subject='a white Ford Explorer (sixth generation) PHEV, front three-quarter'),
    'car-honda-accord-white': dict(src='popular-honda-accord-tenth-generation-6.jpg', floor=None, plates=[[100, 800, 400, 980]],
        subject='a white Honda Accord (tenth generation), front three-quarter'),
    'car-ford-bronco-blue': dict(src='popular-ford-bronco-3.jpg', floor=None, plates=[],
        subject='a blue Ford Bronco (sixth generation) four-door at a show, front three-quarter, show plate only'),
    'car-dodge-charger-orange': dict(src='popular-dodge-charger-3.jpg', floor=None, plates=[[1312, 888, 1562, 976]],
        subject='an orange Dodge Charger (LD) Scat Pack, front three-quarter'),
    'car-porsche-911-gt3-blue': dict(src='popular-porsche-911-3.jpg', floor=None, plates=[],
        subject='a blue Porsche 911 GT3 Touring (991.2) at a show, front three-quarter, show plate only'),
    'car-porsche-911-carrera-rs-orange': dict(src='popular-porsche-911-5.jpg', floor=None, plates=[[1452, 832, 1676, 916]],
        subject='an orange Porsche 911 Carrera RS 2.7 (1972-73), rear three-quarter'),
    'car-tesla-cybertruck': dict(src='popular-tesla-cybertruck-3.jpg', floor=None, plates=[],
        subject='a stainless Tesla Cybertruck Foundation Series (2024), front three-quarter, no plate'),
    'car-range-rover-blue': dict(src='popular-range-rover-1.jpg', floor=None, plates=[[210, 728, 396, 808]],
        subject='a dark blue Range Rover Autobiography (L405), front three-quarter'),
    'car-subaru-outback-white': dict(src='popular-subaru-outback-1.jpg', floor=None, plates=[],
        subject='a white Subaru Outback (BT) Wilderness, front three-quarter, dealer plate only'),
    'car-hyundai-tucson-white': dict(src='popular-hyundai-tucson-2.jpg', floor=None, plates=[[184, 682, 406, 768]],
        subject='a white Hyundai Tucson (NX4), front three-quarter'),
    'car-kia-telluride-grey': dict(src='popular-kia-telluride-1.jpg', floor=None, plates=[[148, 752, 366, 838]],
        subject='a grey Kia Telluride, front three-quarter'),
    'car-rolls-royce-cullinan-black': dict(src='popular-rolls-royce-cullinan-1.jpg', floor=None, plates=[[334, 1026, 446, 1088]],
        subject='a dark grey Rolls-Royce Cullinan, front three-quarter'),
    'car-mercedes-s-class-black': dict(src='popular-mercedes-benz-s-class-4.jpg', floor=None, plates=[[230, 590, 450, 656]],
        subject='a black Mercedes-Benz S-Class (W223), front three-quarter'),
    'car-toyota-tundra-trd-pro-blue': dict(src='trucks-toyota-tundra-5.jpg', floor=None, plates=[[1625, 915, 1715, 1035]],
        subject='a blue Toyota Tundra TRD Pro (2026) in a showroom, front three-quarter'),
    'car-ford-ranger-wildtrak-orange': dict(src='trucks-ford-ranger-1.jpg', floor=None, plates=[[190, 630, 410, 740]],
        subject='an orange Ford Ranger Wildtrak (P703), front three-quarter'),
    'car-ford-f250-black': dict(src='trucks-ford-super-duty-1.jpg', floor=None, plates=[[1604, 664, 1716, 760]],
        subject='a black Ford F-250 Super Duty (P558) crew cab, front three-quarter'),
    'car-nissan-nv200-white': dict(src='vans-nissan-nv200-3.jpg', floor=None, plates=[],
        subject='a white Nissan NV200 van, front three-quarter (its plate is already blank in the photograph)'),
    'car-ford-e350-white': dict(src='vans-ford-e-series-2.jpg', floor=None, plates=[[152, 772, 272, 888]],
        subject='a white 2008 Ford E-Series wagon, front three-quarter'),
    'car-volvo-vnl-blue': dict(src='semis-volvo-vnl-4.jpg', floor=None, plates=[[228, 1080, 300, 1172]],
        subject='a blue Volvo VNL 860 Globetrotter XL sleeper semi tractor, front three-quarter'),
    'car-peterbilt-579-red': dict(src='semis-peterbilt-579-1.jpg', floor=None, plates=[[1496, 1104, 1658, 1156]],
        subject='a red Peterbilt 579 sleeper semi tractor, front three-quarter'),
    # 2026-10-03, round three: top trims, G 63, Prius, Teslas, Rivian, more trucks, 2026 models,
    # collectibles, rare BMW and Porsche
    'car-toyota-prius-white': dict(src='popular-toyota-prius-1.jpg', floor=None, plates=[],
        subject='a white Toyota Prius Plug-in Hybrid (fifth generation), front three-quarter, dealer plate only'),
    'car-mercedes-amg-g63-black': dict(src='popular-mercedes-amg-g-63-1.jpg', floor=None, plates=[[1610, 720, 1810, 810]],
        subject='a matte black Mercedes-AMG G 63 (W463), front three-quarter'),
    'car-mercedes-amg-g63-yellow': dict(src='popular-mercedes-amg-g-63-3.jpg', floor=None, plates=[[1300, 935, 1620, 1035]],
        subject='a yellow Mercedes-AMG G 63 (W465, 2024), front three-quarter'),
    'car-toyota-gr-corolla-black': dict(src='popular-toyota-gr-corolla-3.jpg', floor=None, plates=[],
        subject='a black Toyota GR Corolla, front three-quarter, no front plate'),
    'car-honda-civic-type-r-fl5-white': dict(src='popular-honda-civic-type-r-fl5-1.jpg', floor=None, plates=[[285, 780, 525, 920]],
        subject='a white Honda Civic Type R (FL5, 2023-), front three-quarter'),
    'car-toyota-4runner-trd-pro-lime': dict(src='popular-toyota-4runner-trd-pro-3.jpg', floor=None, plates=[],
        subject='a lime Toyota 4Runner TRD Pro (N280), front three-quarter, no front plate'),
    'car-ford-mustang-dark-horse-blue': dict(src='popular-ford-mustang-dark-horse-3.jpg', floor=None, plates=[],
        subject='a blue Ford Mustang Dark Horse (S650), front three-quarter, show plate only'),
    'car-chevy-corvette-z06-yellow': dict(src='popular-chevrolet-corvette-z06-1.jpg', floor=None, plates=[[1730, 800, 1830, 900]],
        subject='a yellow Chevrolet Corvette Z06 (C7), front three-quarter'),
    'car-cadillac-escalade-v-white': dict(src='popular-cadillac-escalade-v-1.jpg', floor=None, plates=[],
        subject='a white Cadillac Escalade-V (2025), front three-quarter, no plate'),
    'car-bmw-m3-competition-green': dict(src='popular-bmw-m3-competition-g80-1.jpg', floor=None, plates=[[1470, 395, 1690, 495]],
        subject='an Isle of Man green BMW M3 Competition (G80), rear three-quarter'),
    'car-tesla-model-s-plaid-white': dict(src='popular-tesla-model-s-plaid-3.jpg', floor=None, plates=[],
        subject='a white Tesla Model S Plaid, front three-quarter, no front plate'),
    'car-tesla-model-x-silver': dict(src='popular-tesla-model-x-1.jpg', floor=None, plates=[[1480, 700, 1720, 790]],
        subject='a silver Tesla Model X, front three-quarter'),
    'car-audi-rs5-sportback-red': dict(src='popular-audi-rs-5-sportback-3.jpg', floor=None, plates=[[160, 650, 410, 780]],
        subject='a red Audi RS 5 Sportback (F5, facelift), front three-quarter; dealer plate blurred'),
    'car-hyundai-sonata-black': dict(src='popular-hyundai-sonata-2.jpg', floor=None, plates=[],
        subject='a black Hyundai Sonata (DN8, 2024 facelift), front three-quarter, plate already blank'),
    'car-mazda-cx5-blue': dict(src='popular-mazda-cx-5-3.jpg', floor=None, plates=[[210, 760, 510, 880]],
        subject='a deep blue Mazda CX-5 (KF, 2022 facelift), front three-quarter; dealer plate blurred'),
    'car-jeep-grand-cherokee-l-silver': dict(src='popular-jeep-grand-cherokee-3.jpg', floor=None, plates=[[190, 700, 440, 800]],
        subject='a silver Jeep Grand Cherokee L (WL), front three-quarter; dealer plate blurred'),
    'car-honda-pilot-white': dict(src='popular-honda-pilot-3.jpg', floor=None, plates=[],
        subject='a white Honda Pilot (third generation), front three-quarter, no front plate'),
    'car-toyota-sienna-white': dict(src='popular-toyota-sienna-3.jpg', floor=None, plates=[[210, 1010, 370, 1120]],
        subject='a white Toyota Sienna (XL40, 2021-) minivan, front three-quarter'),
    'car-chevy-equinox-white': dict(src='popular-chevrolet-equinox-3.jpg', floor=None, plates=[],
        subject='a white Chevrolet Equinox (third generation, 2022), front three-quarter, no front plate'),
    'car-lexus-rx-white': dict(src='popular-lexus-rx-1.jpg', floor=None, plates=[[1510, 660, 1770, 745]],
        subject='a white Lexus RX (fifth generation, 2023-), front three-quarter'),
    'car-mercedes-amg-gle63-silver': dict(src='popular-mercedes-benz-gle-1.jpg', floor=None, plates=[],
        subject='a silver Mercedes-AMG GLE 63 S (V167), front three-quarter, plate already removed'),
    'car-subaru-forester-silver': dict(src='popular-subaru-forester-1.jpg', floor=None, plates=[],
        subject='a silver Subaru Forester (sixth generation, 2025-), front three-quarter, model-name show plate'),
    'car-kia-k5-grey': dict(src='popular-kia-k5-2.jpg', floor=None, plates=[],
        subject='a grey Kia K5 (DL3, facelift), front three-quarter, plate already blank'),
    'car-chevy-silverado-zr2-red': dict(src='trucks-chevrolet-silverado-zr2-1.jpg', floor=None, plates=[[1700, 740, 1800, 860]],
        subject='a red Chevrolet Silverado 1500 ZR2 (2022-) crew cab pickup, front three-quarter'),
    'car-gmc-sierra-denali-grey': dict(src='trucks-gmc-sierra-denali-2.jpg', floor=None, plates=[[115, 740, 300, 830]],
        subject='a grey GMC Sierra 1500 Denali (2016-18) crew cab pickup, front three-quarter'),
    'car-ford-f150-lightning-black': dict(src='trucks-ford-f-150-lightning-3.jpg', floor=None, plates=[[120, 710, 205, 810]],
        subject='a black Ford F-150 Lightning crew cab pickup, front three-quarter'),
    'car-ram-2500-power-wagon-white': dict(src='trucks-ram-2500-power-wagon-1.jpg', floor=None, plates=[],
        subject='a white Ram 2500 Power Wagon (2026) crew cab pickup, front three-quarter, no front plate'),
    'car-nissan-frontier-grey': dict(src='trucks-nissan-frontier-1.jpg', floor=None, plates=[[190, 810, 460, 930]],
        subject='a grey Nissan Frontier PRO-4X (D41, 2022-) crew cab pickup, front three-quarter; dealer plate blurred'),
    'car-jeep-gladiator-green': dict(src='trucks-jeep-gladiator-2.jpg', floor=None, plates=[[320, 625, 535, 710]],
        subject='a green Jeep Gladiator (JT) pickup, rear three-quarter'),
    'car-ford-maverick-red': dict(src='trucks-ford-maverick-1.jpg', floor=None, plates=[[130, 765, 330, 855]],
        subject='a red Ford Maverick Tremor pickup, front three-quarter'),
    'car-honda-ridgeline-white': dict(src='trucks-honda-ridgeline-1.jpg', floor=None, plates=[],
        subject='a white Honda Ridgeline (second generation) pickup, front three-quarter, no front plate'),
    'car-ford-f150-raptor-2026-black': dict(src='y2026-2026-ford-f-150-raptor-1.jpg', floor=None, plates=[[80, 740, 270, 890]],
        subject='a black Ford F-150 Raptor (2026) crew cab pickup with a roof rack, front three-quarter'),
    'car-toyota-supra-a80-silver': dict(src='collect-toyota-supra-a80-1.jpg', floor=None, plates=[],
        subject='a silver Toyota Supra (A80, 1993-2002), rear three-quarter, plate already blank'),
    'car-nissan-skyline-gtr-r34-blue': dict(src='collect-nissan-skyline-gt-r-r34-2.jpg', floor=None, plates=[[240, 715, 450, 835]],
        subject='a Bayside Blue Nissan Skyline GT-R (R34), front three-quarter'),
    'car-honda-nsx-na1-red': dict(src='collect-honda-nsx-na1-3.jpg', floor=None, plates=[],
        subject='a red Honda NSX (NA1, 1991) in a museum, front three-quarter, museum plate only'),
    'car-honda-s2000-silver': dict(src='collect-honda-s2000-1.jpg', floor=None, plates=[[1560, 630, 1780, 730]],
        subject='a silver Honda S2000 with a hard top, front three-quarter'),
    'car-toyota-land-cruiser-fj40-green': dict(src='collect-toyota-land-cruiser-fj40-2.jpg', floor=None, plates=[],
        subject='a green Toyota Land Cruiser FJ40 at a show, front three-quarter, show plate only'),
    'car-toyota-land-cruiser-80-red': dict(src='collect-toyota-land-cruiser-80-2.jpg', floor=None, plates=[[440, 720, 650, 810]],
        subject='a red Toyota Land Cruiser 80, front three-quarter'),
    'car-ford-bronco-1st-gen-cream': dict(src='collect-ford-bronco-first-generation-1.jpg', floor=None, plates=[],
        subject='a cream first-generation Ford Bronco (1966-77), front three-quarter, no front plate'),
    'car-chevy-camaro-1969-silver': dict(src='collect-chevrolet-camaro-1969-4.jpg', floor=None, plates=[],
        subject='a silver 1969 Chevrolet Camaro Z/28, front three-quarter, no front plate'),
    'car-land-rover-defender-90-teal': dict(src='collect-land-rover-defender-90-2.jpg', floor=None, plates=[[1235, 860, 1345, 910]],
        subject='a teal Land Rover Defender 90 station wagon (classic, 1983-2016), front three-quarter'),
    'car-mercedes-190e-evo-black': dict(src='collect-mercedes-benz-190-e-2-5-16-evolution-1.jpg', floor=None, plates=[[245, 805, 545, 935]],
        subject='a black Mercedes-Benz 190 E 2.5-16 Evolution, front three-quarter'),
    'car-bmw-m3-csl-e46-grey': dict(src='collect-bmw-m3-csl-e46-1.jpg', floor=None, plates=[[200, 730, 470, 870]],
        subject='a grey BMW M3 CSL (E46), front three-quarter'),
    'car-bmw-z8-silver': dict(src='collect-bmw-z8-2.jpg', floor=None, plates=[[310, 780, 640, 880]],
        subject='a silver BMW Z8 roadster, front three-quarter'),
    'car-bmw-2002-turbo-white': dict(src='collect-bmw-2002-turbo-1.jpg', floor=None, plates=[[310, 870, 560, 980]],
        subject='a white BMW 2002 turbo (1973-74), front three-quarter'),
    'car-bmw-3-0-csl-beige': dict(src='collect-bmw-3-0-csl-4.jpg', floor=None, plates=[],
        subject='a beige BMW 3.0 CSL (E9) at a show, side on, no plate'),
    'car-bmw-1m-coupe-orange': dict(src='collect-bmw-1-series-m-coupe-2.jpg', floor=None, plates=[[1480, 775, 1760, 890]],
        subject='a Valencia orange BMW 1 Series M Coupe, front three-quarter'),
    'car-porsche-911-gt2-rs-white': dict(src='collect-porsche-911-gt2-rs-4.jpg', floor=None, plates=[[175, 720, 430, 820]],
        subject='a white Porsche 911 GT2 RS (991) with Manthey kit, front three-quarter'),
    'car-porsche-918-spyder-white': dict(src='collect-porsche-918-spyder-3.jpg', floor=None, plates=[],
        subject='a white Porsche 918 Spyder, front three-quarter, no front plate'),
    'car-porsche-carrera-gt-silver': dict(src='collect-porsche-carrera-gt-3.jpg', floor=None, plates=[[1390, 1015, 1730, 1110]],
        subject='a silver Porsche Carrera GT, front three-quarter; dealer plate blurred'),
    'car-porsche-911-sport-classic-grey': dict(src='collect-porsche-911-sport-classic-3.jpg', floor=None, plates=[[1240, 670, 1430, 790]],
        subject='a grey Porsche 911 Sport Classic (992), rear three-quarter'),
    'car-porsche-356-blue': dict(src='collect-porsche-356-1.jpg', floor=None, plates=[[1440, 880, 1650, 980]],
        subject='a blue Porsche 356 cabriolet, front three-quarter'),
    'car-jeep-wrangler-rubicon-2026-orange': dict(src='y2026-2026-jeep-wrangler-3.jpg', floor=None, plates=[],
        subject='an orange Jeep Wrangler Rubicon (2024-26), front three-quarter, no front plate'),
    'car-jeep-grand-wagoneer-white': dict(src='y2026-2026-jeep-grand-wagoneer-1.jpg', floor=None, plates=[],
        subject='a white Jeep Grand Wagoneer L (2026), front three-quarter, no front plate'),
    'car-lamborghini-temerario-yellow': dict(src='y2026-2026-lamborghini-temerario-2.jpg', floor=None, plates=[],
        subject='a yellow Lamborghini Temerario (2026), front three-quarter, no front plate'),
    'car-toyota-gr-supra-2026-red': dict(src='y2026-2026-toyota-gr-supra-2.jpg', floor=None, plates=[],
        subject='a matte red Toyota GR Supra (2026) on a showroom floor, front three-quarter, no plate'),
    'car-toyota-prius-2026-grey': dict(src='y2026-2026-toyota-prius-3.jpg', floor=None, plates=[[250, 780, 360, 930]],
        subject='a grey Toyota Prius (2026) on a showroom floor, front three-quarter; dealer plate blurred'),
    'car-kia-k4-white': dict(src='y2026-2026-kia-k4-1.jpg', floor=None, plates=[[170, 740, 400, 830]],
        subject='a white Kia K4 hatchback (2026), front three-quarter; dealer plate blurred'),
    'car-hyundai-ioniq-9-white': dict(src='y2026-2026-hyundai-ioniq-9-1.jpg', floor=None, plates=[[175, 800, 385, 880]],
        subject='a white Hyundai Ioniq 9 (2026), front three-quarter'),
    'car-rivian-r1s-silver': dict(src='y2026-rivian-r1s-2.jpg', floor=None, plates=[[225, 895, 365, 1000]],
        subject='a silver Rivian R1S, front three-quarter'),
    'car-tesla-cybertruck-cyberbeast': dict(src='y2026-tesla-cybertruck-cyberbeast-1.jpg', floor=None, plates=[[100, 850, 330, 920]],
        subject='a stainless Tesla Cybertruck Cyberbeast, rear three-quarter'),
    # 2026-10-03 (owner: "As much modern apple imagery as you can"): photographs of
    # the devices we buy, from Commons, for the angles the storefront art lacks
    'photo-iphone-13-pro-graphite': dict(src='apple-iphone-13-pro-2.jpg', floor=None, plates=[],
        subject='an iPhone 13 Pro and 13 Pro Max in graphite, back and screen, on a dark cloth'),
    'photo-iphone-14-pro-deep-purple': dict(src='apple-iphone-14-pro-1.jpg', floor=None, plates=[],
        subject='an iPhone 14 Pro in Deep Purple, back'),
    'photo-iphone-14-red': dict(src='apple-iphone-14-1.jpg', floor=None, plates=[],
        subject='an iPhone 14 (PRODUCT)RED, back'),
    'photo-iphone-15-black': dict(src='apple-iphone-15-1.jpg', floor=None, plates=[],
        subject='an iPhone 15 in black, back, flat'),
    'photo-iphone-17-pro-silver': dict(src='apple-iphone-17-pro-1.jpg', floor=None, plates=[], upright=59.3,
        subject='an iPhone 17 Pro in silver, back, turned upright (it lay at 31 degrees; owner, 2026-10-04: '
                '"the angle is a little weird")'),
    'photo-ipad-a16-pink': dict(src='apple-ipad-a16-4.jpg', floor=None, plates=[],
        subject='an iPad (A16) in pink, back'),
    'photo-ipad-air-m2-blue': dict(src='apple-ipad-air-m2-4.jpg', floor=None, plates=[],
        subject='an iPad Air 11-inch (M2) in blue, back'),
    'photo-ipad-mini-6-blue': dict(src='apple-ipad-mini-6-4.jpg', floor=None, plates=[],
        subject='an iPad mini 6 in blue, back'),
    'photo-mac-studio-angle': dict(src='apple-mac-studio-4.jpg', floor=None, plates=[],
        subject='a Mac Studio (2022), front three-quarter from above, logo on top'),
    'photo-macbook-air-15-starlight': dict(src='apple-macbook-air-15-inch-3.jpg', floor=None, plates=[],
        subject='a MacBook Air 15-inch in Starlight, open, three-quarter'),
    'photo-macbook-air-m1-silver': dict(src='apple-macbook-air-m1-2.jpg', floor=None, plates=[],
        subject='a MacBook Air (M1) in silver, open, three-quarter, screen off'),
    'photo-macbook-air-m1-space-gray': dict(src='apple-macbook-air-m1-3.jpg', floor=None, plates=[],
        subject='a MacBook Air (M1) in space gray, open, from the front, screen off'),
    'photo-macbook-air-m2-starlight': dict(src='apple-macbook-air-m2-1.jpg', floor=None, plates=[],
        subject='a MacBook Air (M2) in Starlight, open, three-quarter'),
    'photo-macbook-air-m2-lid': dict(src='apple-macbook-air-m2-4.jpg', floor=None, plates=[],
        subject='a MacBook Air (M2) closed, lid and logo from above'),
    # 2026-10-03 (owner: "more alternate angles as much as you can"): rear and side views
    'car-bmw-m3-touring-blue-rear': dict(src='angles-bmw-m3-rear-1.jpg', floor=None, plates=[[1395, 455, 1670, 545]],
        subject='a blue BMW M3 Touring (G81), rear three-quarter'),
    'car-bmw-x5-black-rear': dict(src='angles-bmw-x5-rear-1.jpg', floor=None, plates=[[355, 725, 545, 820]],
        subject='a black BMW X5 (G05), rear three-quarter'),
    'car-cadillac-escalade-black-rear': dict(src='angles-cadillac-escalade-rear-1.jpg', floor=None, plates=[[1390, 555, 1535, 665]],
        subject='a black Cadillac Escalade (fifth generation), rear three-quarter'),
    'car-chevy-equinox-white-rear': dict(src='angles-chevrolet-equinox-rear-2.jpg', floor=None, plates=[[1455, 510, 1680, 635]],
        subject='a white Chevrolet Equinox (third generation), rear three-quarter; dealer plate blurred'),
    'car-ford-bronco-sport-yellow-rear': dict(src='angles-ford-bronco-rear-3.jpg', floor=None, plates=[[1510, 825, 1680, 965]],
        subject='a yellow Ford Bronco Sport, rear three-quarter'),
    'car-ford-f150-raptor-orange-rear': dict(src='angles-ford-f-150-raptor-rear-1.jpg', floor=None, plates=[[440, 785, 605, 885]],
        subject='an orange Ford F-150 Raptor (third generation), rear three-quarter'),
    'car-ford-f150-black-rear': dict(src='angles-ford-f-150-rear-3.jpg', floor=None, plates=[[255, 595, 385, 700]],
        subject='a black Ford F-150 FX4 (thirteenth generation), rear three-quarter'),
    'car-ford-mustang-mach1-grey-rear': dict(src='angles-ford-mustang-rear-1.jpg', floor=None, plates=[[350, 640, 680, 755]],
        subject='a grey Ford Mustang Mach 1 (S550), rear three-quarter'),
    'car-ford-mustang-gt-yellow-rear': dict(src='angles-ford-mustang-rear-2.jpg', floor=None, plates=[[195, 585, 495, 715]],
        subject='a yellow Ford Mustang GT (S550), rear three-quarter'),
    'car-ford-ranger-blue-rear': dict(src='angles-ford-ranger-rear-1.jpg', floor=None, plates=[[1550, 625, 1655, 725]],
        subject='a blue Ford Ranger Limited (P703) double cab, rear three-quarter'),
    'car-ford-transit-custom-silver-rear': dict(src='angles-ford-transit-rear-2.jpg', floor=None, plates=[[1440, 620, 1640, 710]],
        subject='a silver Ford Transit Custom (second generation) panel van, rear three-quarter'),
    'car-ford-e-transit-custom-white-rear': dict(src='angles-ford-transit-rear-3.jpg', floor=None, plates=[[155, 680, 370, 780]],
        subject='a white Ford E-Transit Custom (second generation), rear three-quarter'),
    'car-gmc-sierra-ev-grey-rear': dict(src='angles-gmc-sierra-rear-1.jpg', floor=None, plates=[],
        subject='a grey GMC Sierra EV Denali pickup, rear three-quarter, no plate'),
    'car-honda-accord-white-rear': dict(src='angles-honda-accord-rear-1.jpg', floor=None, plates=[],
        subject='a white Honda Accord (tenth generation), rear three-quarter, plate already blank'),
    'car-honda-accord-2023-white-side': dict(src='angles-honda-accord-side-view-3.jpg', floor=None, plates=[],
        subject='a white Honda Accord (eleventh generation, 2023-), side on'),
    'car-honda-crv-red-rear': dict(src='angles-honda-cr-v-rear-1.jpg', floor=None, plates=[[205, 545, 340, 650]],
        subject='a red Honda CR-V (sixth generation, 2023-), rear three-quarter; dealer plate blurred'),
    'car-honda-pilot-white-rear': dict(src='angles-honda-pilot-rear-2.jpg', floor=None, plates=[[1725, 360, 1825, 470]],
        subject='a white Honda Pilot (second generation), rear three-quarter'),
    'car-honda-ridgeline-grey-rear': dict(src='angles-honda-ridgeline-rear-2.jpg', floor=None, plates=[[1465, 645, 1640, 770]],
        subject='a grey Honda Ridgeline (second generation) pickup, rear three-quarter; dealer plate blurred'),
    'car-hyundai-ioniq5-grey-rear': dict(src='angles-hyundai-ioniq-5-rear-1.jpg', floor=None, plates=[[1485, 600, 1715, 700]],
        subject='a grey Hyundai Ioniq 5 (facelift), rear three-quarter'),
    'car-hyundai-ioniq5-silver-side': dict(src='angles-hyundai-ioniq-5-side-view-1.jpg', floor=None, plates=[[1590, 930, 1710, 1005]],
        subject='a silver Hyundai Ioniq 5, front three-quarter, side on'),
    'car-hyundai-tucson-l-white-rear': dict(src='angles-hyundai-tucson-rear-2.jpg', floor=None, plates=[[385, 425, 615, 545]],
        subject='a white Hyundai Tucson L (NX4, long wheelbase), rear three-quarter'),
    'car-jeep-gladiator-rubicon-red-side': dict(src='angles-jeep-gladiator-side-view-1.jpg', floor=None, plates=[],
        subject='a red Jeep Gladiator Rubicon (JT) pickup, side on, no plate in view'),
    'car-kia-k5-silver-rear': dict(src='angles-kia-k5-rear-1.jpg', floor=None, plates=[[1680, 605, 1795, 700]],
        subject='a silver Kia K5 (DL3), rear three-quarter; dealer plate blurred'),
    'car-kia-telluride-2026-silver-rear': dict(src='angles-kia-telluride-rear-1.jpg', floor=None, plates=[[170, 610, 320, 705]],
        subject='a silver Kia Telluride (second generation, 2026), rear three-quarter; dealer plate blurred'),
    'car-lexus-rx-grey-rear': dict(src='angles-lexus-rx-rear-2.jpg', floor=None, plates=[[225, 500, 490, 595]],
        subject='a grey Lexus RX 350h (fifth generation), rear three-quarter'),
    'car-lexus-rx-white-rear': dict(src='angles-lexus-rx-rear-3.jpg', floor=None, plates=[[205, 470, 440, 590]],
        subject='a white Lexus RX 500h (fifth generation), rear three-quarter'),
    'car-ram-1500-black-rear': dict(src='angles-ram-1500-rear-1.jpg', floor=None, plates=[[405, 635, 555, 760]],
        subject='a black Ram 1500 (2025) crew cab pickup, rear three-quarter; dealer plate blurred'),
    'car-rivian-r1s-grey-rear': dict(src='angles-rivian-r1s-rear-1.jpg', floor=None, plates=[[200, 630, 350, 750]],
        subject='a grey Rivian R1S, rear three-quarter'),
    'car-rivian-r1t-white-rear': dict(src='angles-rivian-r1t-rear-1.jpg', floor=None, plates=[[300, 640, 430, 740]],
        subject='a white Rivian R1T pickup, rear three-quarter'),
    'car-rivian-r1t-green-rear': dict(src='angles-rivian-r1t-rear-2.jpg', floor=None, plates=[[1600, 740, 1730, 850], [1400, 735, 1500, 820]],
        subject='a green Rivian R1T pickup with a roof rack, rear three-quarter'),
    'car-subaru-outback-red-rear': dict(src='angles-subaru-outback-rear-2.jpg', floor=None, plates=[[195, 485, 330, 610]],
        subject='a red Subaru Outback (BT), rear three-quarter; dealer plate blurred'),
    'car-tesla-cybertruck-rear-street': dict(src='angles-tesla-cybertruck-rear-2.jpg', floor=None, plates=[[345, 540, 470, 635]],
        subject='a stainless Tesla Cybertruck, rear three-quarter'),
    'car-tesla-model-3-performance-white-rear': dict(src='angles-tesla-model-3-rear-3.jpg', floor=None, plates=[[265, 585, 470, 720]],
        subject='a white Tesla Model 3 Performance (Highland) in a showroom, rear three-quarter'),
    'car-tesla-model-x-white-rear': dict(src='angles-tesla-model-x-rear-1.jpg', floor=None, plates=[[1550, 370, 1690, 480]],
        subject='a white Tesla Model X, rear three-quarter'),
    'car-tesla-model-y-red-side': dict(src='angles-tesla-model-y-side-view-1.jpg', floor=None, plates=[],
        subject='a red Tesla Model Y (Juniper), side on, no plate in view'),
    'car-toyota-camry-2025-white-side': dict(src='angles-toyota-camry-side-view-2.jpg', floor=None, plates=[],
        subject='a white Toyota Camry (XV80, 2025-), side on'),
    'car-toyota-corolla-cross-silver-rear': dict(src='angles-toyota-corolla-rear-1.jpg', floor=None, plates=[[230, 465, 480, 575]],
        subject='a silver Toyota Corolla Cross Hybrid, rear three-quarter'),
    'car-toyota-gr-supra-grey-rear': dict(src='angles-toyota-gr-supra-rear-1.jpg', floor=None, plates=[[340, 515, 650, 665]],
        subject='a grey Toyota GR Supra (A90) in a showroom, rear three-quarter; dealer plate blurred'),
    'car-toyota-highlander-white-rear': dict(src='angles-toyota-highlander-rear-2.jpg', floor=None, plates=[],
        subject='a white Toyota Highlander (XU70), rear three-quarter, plate already blank'),
    'car-toyota-highlander-silver-rear': dict(src='angles-toyota-highlander-rear-3.jpg', floor=None, plates=[[1490, 435, 1620, 545]],
        subject='a silver Toyota Highlander (XU70), rear three-quarter; dealer plate blurred'),
    'car-toyota-prius-silver-rear': dict(src='angles-toyota-prius-rear-1.jpg', floor=None, plates=[[180, 705, 325, 825]],
        subject='a silver Toyota Prius (fifth generation), rear three-quarter; dealer plate blurred'),
    'car-toyota-prius-grey-rear': dict(src='angles-toyota-prius-rear-2.jpg', floor=None, plates=[[1440, 875, 1585, 995]],
        subject='a grey Toyota Prius XLE (fifth generation), rear three-quarter; dealer plate blurred'),
    'car-toyota-rav4-2026-white-rear': dict(src='angles-toyota-rav4-rear-3.jpg', floor=None, plates=[],
        subject='a white Toyota RAV4 PHEV (sixth generation, 2026) at a show, rear three-quarter, show plate only'),
    'car-toyota-tacoma-trd-black-rear': dict(src='angles-toyota-tacoma-rear-2.jpg', floor=None, plates=[],
        subject='a black Toyota Tacoma TRD Off-Road (N400, 2024-), rear three-quarter, plate already blank'),
    'car-toyota-tundra-trd-pro-white-rear': dict(src='angles-toyota-tundra-rear-1.jpg', floor=None, plates=[],
        subject='a white Toyota Tundra TRD Pro build with spare tyres in the bed, at a show, rear three-quarter, show plate only'),
    # 2026-10-04 (owner: "more variety?": more car models and colours): the popular2 fetch,
    # three photographs each of 98 more models; plates boxed by eye on the 1920px photograph
    'car-acura-integra-red-rear': dict(src='popular2-acura-integra-2.jpg', floor=None, plates=[],
        subject='a red Acura Integra (2023-) A-Spec, rear three-quarter (its plate is the dealer\'s Acura card)'),
    'car-acura-rdx-blue': dict(src='popular2-acura-rdx-1.jpg', floor=None, plates=[[220, 715, 500, 805]],
        subject='a dark blue Acura RDX (third generation, 2019-), front three-quarter'),
    'car-acura-rdx-blue-rear': dict(src='popular2-acura-rdx-2.jpg', floor=None, plates=[[1405, 480, 1670, 575]],
        subject='a dark blue Acura RDX (third generation, 2019-), rear three-quarter'),
    'car-aston-martin-db11-grey': dict(src='popular2-aston-martin-db11-2.jpg', floor=None, plates=[[1380, 770, 1690, 880]],
        subject='a grey Aston Martin DB11 coupe, front three-quarter'),
    'car-audi-e-tron-gt-grey-rear': dict(src='popular2-audi-e-tron-gt-2.jpg', floor=None, plates=[[1510, 445, 1735, 545]],
        subject='a grey Audi S e-tron GT (2024-), rear three-quarter'),
    'car-audi-q5-sportback-grey': dict(src='popular2-audi-q5-1.jpg', floor=None, plates=[],
        subject='a grey Audi SQ5 Sportback (third generation, 2025-), front three-quarter (no plate on it)'),
    'car-audi-q5-sportback-grey-rear': dict(src='popular2-audi-q5-2.jpg', floor=None, plates=[[1610, 440, 1790, 545]],
        subject='a grey Audi Q5 Sportback (third generation, 2025-), rear three-quarter'),
    'car-audi-q7-grey': dict(src='popular2-audi-q7-3.jpg', floor=None, plates=[[320, 885, 690, 1000]],
        subject='a grey Audi Q7 (2024 facelift), front three-quarter'),
    'car-audi-r8-v10-blue': dict(src='popular2-audi-r8-2.jpg', floor=None, plates=[],
        subject='a blue Audi R8 V10 (second generation), front three-quarter (no plate on it)'),
    'car-bentley-continental-gt-green': dict(src='popular2-bentley-continental-gt-1.jpg', floor=None, plates=[],
        subject='a green Bentley Continental GT (fourth generation, 2024-), front three-quarter (no plate on it)'),
    'car-bentley-continental-gt-green-rear': dict(src='popular2-bentley-continental-gt-2.jpg', floor=None, plates=[],
        subject='a green Bentley Continental GT (fourth generation, 2024-), rear three-quarter (no plate on it)'),
    'car-bentley-continental-gt-red-rear': dict(src='popular2-bentley-continental-gt-3.jpg', floor=None, plates=[[215, 535, 500, 655]],
        subject='a red Bentley Continental GT Speed (third generation), rear three-quarter'),
    'car-bmw-5-series-grey': dict(src='popular2-bmw-5-series-3.jpg', floor=None, plates=[[1330, 520, 1545, 610]],
        subject='a grey BMW 5 Series (G30) M Sport sedan, front three-quarter'),
    'car-bmw-i4-white-rear': dict(src='popular2-bmw-i4-2.jpg', floor=None, plates=[[240, 625, 495, 720]],
        subject='a white BMW i4 M50 Gran Coupe, rear three-quarter'),
    'car-bmw-i4-m50-blue': dict(src='popular2-bmw-i4-3.jpg', floor=None, plates=[[1455, 690, 1735, 795]],
        subject='a matte blue BMW i4 M50 Gran Coupe, front three-quarter'),
    'car-bmw-m4-convertible-black': dict(src='popular2-bmw-m4-3.jpg', floor=None, plates=[[150, 630, 400, 760]],
        subject='a black BMW M4 Competition Convertible (G83), front three-quarter'),
    'car-bmw-x3-m50-black-rear': dict(src='popular2-bmw-x3-1.jpg', floor=None, plates=[[215, 660, 485, 770]],
        subject='a black BMW X3 M50 (G45, 2025-), rear three-quarter'),
    'car-bmw-x3-black': dict(src='popular2-bmw-x3-2.jpg', floor=None, plates=[[315, 858, 685, 985]],
        subject='a black BMW X3 (G45, 2025-) M Sport, front three-quarter'),
    'car-bmw-ix3-2026-white': dict(src='popular2-bmw-x3-3.jpg', floor=None, plates=[],
        subject='a white BMW iX3 (Neue Klasse, 2026), front three-quarter (show placard, no plate)'),
    'car-bmw-x7-white': dict(src='popular2-bmw-x7-1.jpg', floor=None, plates=[[145, 725, 380, 812]],
        subject='a white BMW X7 (G07, 2022 facelift) M Sport, front three-quarter'),
    'car-bmw-x7-m50i-white': dict(src='popular2-bmw-x7-3.jpg', floor=None, plates=[[1550, 620, 1810, 710]],
        subject='a white BMW X7 M50i (G07), front three-quarter'),
    'car-buick-enclave-grey': dict(src='popular2-buick-enclave-2.jpg', floor=None, plates=[[230, 718, 540, 845]],
        subject='a grey Buick Enclave (second generation), front three-quarter'),
    'car-buick-enclave-grey-rear': dict(src='popular2-buick-enclave-3.jpg', floor=None, plates=[[1290, 535, 1615, 645]],
        subject='a grey Buick Enclave (second generation), rear three-quarter'),
    'car-chevy-camaro-yellow-rear': dict(src='popular2-chevrolet-camaro-2.jpg', floor=None, plates=[[1345, 680, 1550, 775]],
        subject='a yellow Chevrolet Camaro SS (fifth generation), rear three-quarter'),
    'car-chevy-camaro-yellow': dict(src='popular2-chevrolet-camaro-3.jpg', floor=None, plates=[[975, 880, 1250, 970]],
        subject='a yellow Chevrolet Camaro SS (fifth generation), front three-quarter'),
    'car-chevy-suburban-black': dict(src='popular2-chevrolet-suburban-3.jpg', floor=None, plates=[[1210, 1128, 1375, 1232]],
        subject='a black Chevrolet Suburban (twelfth generation, 2021-), front three-quarter from above'),
    'car-chrysler-pacifica-grey': dict(src='popular2-chrysler-pacifica-2.jpg', floor=None, plates=[[230, 860, 520, 975]],
        subject='a grey Chrysler Pacifica (2021 facelift) minivan, front three-quarter'),
    'car-chrysler-pacifica-white-rear': dict(src='popular2-chrysler-pacifica-3.jpg', floor=None, plates=[[240, 520, 490, 615]],
        subject='a white Chrysler Pacifica (2021 facelift) minivan, rear three-quarter'),
    'car-dodge-challenger-1972-lime': dict(src='popular2-dodge-challenger-1.jpg', floor=None, plates=[[805, 700, 1120, 915]],
        subject='a lime green Dodge Challenger (first generation, 1972), head-on'),
    'car-dodge-durango-srt-grey': dict(src='popular2-dodge-durango-1.jpg', floor=None, plates=[[155, 790, 405, 900]],
        subject='a grey Dodge Durango SRT (third generation, 2021 facelift), front three-quarter'),
    'car-ferrari-296-gtb-yellow': dict(src='popular2-ferrari-296-1.jpg', floor=None, plates=[[175, 680, 470, 790]],
        subject='a yellow Ferrari 296 GTB, front three-quarter'),
    'car-ferrari-296-gtb-yellow-rear': dict(src='popular2-ferrari-296-2.jpg', floor=None, plates=[[185, 505, 405, 608]],
        subject='a yellow Ferrari 296 GTB, rear three-quarter'),
    'car-ferrari-296-gts-grey': dict(src='popular2-ferrari-296-3.jpg', floor=None, plates=[[155, 560, 415, 668]],
        subject='a grey Ferrari 296 GTS with a yellow stripe, front three-quarter'),
    'car-ferrari-f8-tributo-red': dict(src='popular2-ferrari-f8-1.jpg', floor=None, plates=[[190, 728, 420, 825]],
        subject='a red Ferrari F8 Tributo, front three-quarter'),
    'car-ferrari-f8-tributo-red-rear': dict(src='popular2-ferrari-f8-3.jpg', floor=None, plates=[[1405, 512, 1645, 612]],
        subject='a red Ferrari F8 Tributo, rear three-quarter'),
    'car-ferrari-f8-spider-magenta-rear': dict(src='popular2-ferrari-f8-2.jpg', floor=None, plates=[[1420, 712, 1685, 802]],
        subject='a magenta Ferrari F8 Spider, rear three-quarter'),
    'car-ferrari-roma-white': dict(src='popular2-ferrari-roma-3.jpg', floor=None, plates=[[175, 842, 445, 955]],
        subject='a white Ferrari Roma, front three-quarter'),
    'car-ford-mustang-mach-e-gt-orange': dict(src='popular2-ford-mustang-mach-e-1.jpg', floor=None, plates=[],
        subject='an orange Ford Mustang Mach-E GT, front three-quarter (show placard, no plate)'),
    'car-ford-mustang-mach-e-rally-lime': dict(src='popular2-ford-mustang-mach-e-2.jpg', floor=None, plates=[],
        subject='a lime Ford Mustang Mach-E Rally, front three-quarter (show placard, no plate)'),
    'car-genesis-g70-grey-rear': dict(src='popular2-genesis-g70-3.jpg', floor=None, plates=[[175, 620, 430, 735]],
        subject='a grey Genesis G70 (2021 facelift) sedan, rear three-quarter'),
    'car-genesis-gv80-grey': dict(src='popular2-genesis-gv80-1.jpg', floor=None, plates=[[255, 645, 540, 750]],
        subject='a matte grey Genesis GV80, front three-quarter'),
    'car-gmc-yukon-denali-white-rear': dict(src='popular2-gmc-yukon-1.jpg', floor=None, plates=[[1475, 445, 1685, 540]],
        subject='a white GMC Yukon XL Denali (fifth generation, 2021-), rear three-quarter'),
    'car-gmc-yukon-denali-2025-black-rear': dict(src='popular2-gmc-yukon-3.jpg', floor=None, plates=[[175, 775, 310, 850]],
        subject='a black GMC Yukon Denali (2025 facelift), rear three-quarter'),
    'car-honda-hrv-red-rear': dict(src='popular2-honda-hr-v-2.jpg', floor=None, plates=[[1450, 680, 1715, 790]],
        subject='a red Honda HR-V (third generation), rear three-quarter'),
    'car-honda-hrv-beige': dict(src='popular2-honda-hr-v-3.jpg', floor=None, plates=[[205, 800, 490, 920]],
        subject='a sand beige Honda HR-V (third generation), front three-quarter'),
    'car-honda-passport-white': dict(src='popular2-honda-passport-1.jpg', floor=None, plates=[[1555, 800, 1695, 895]],
        subject='a white Honda Passport (2022 facelift) TrailSport, front three-quarter'),
    'car-hyundai-ioniq-6-silver': dict(src='popular2-hyundai-ioniq-6-1.jpg', floor=None, plates=[[215, 692, 495, 805]],
        subject='a silver Hyundai Ioniq 6 (2025 facelift), front three-quarter'),
    'car-hyundai-ioniq-6-silver-rear': dict(src='popular2-hyundai-ioniq-6-3.jpg', floor=None, plates=[[1410, 762, 1705, 905]],
        subject='a silver Hyundai Ioniq 6 (2025 facelift), rear three-quarter'),
    'car-hyundai-kona-n-white': dict(src='popular2-hyundai-kona-1.jpg', floor=None, plates=[[120, 625, 360, 750]],
        subject='a white Hyundai Kona N, front three-quarter'),
    'car-hyundai-kona-n-white-rear': dict(src='popular2-hyundai-kona-2.jpg', floor=None, plates=[[1400, 530, 1675, 640]],
        subject='a white Hyundai Kona N, rear three-quarter'),
    'car-hyundai-kona-grey': dict(src='popular2-hyundai-kona-3.jpg', floor=None, plates=[[185, 660, 445, 770]],
        subject='a grey Hyundai Kona (second generation, 2023-), front three-quarter'),
    'car-hyundai-palisade-black': dict(src='popular2-hyundai-palisade-2.jpg', floor=None, plates=[[65, 750, 285, 870]],
        subject='a black Hyundai Palisade Calligraphy (2023 facelift), front three-quarter'),
    'car-hyundai-palisade-white': dict(src='popular2-hyundai-palisade-3.jpg', floor=None, plates=[],
        subject='a white Hyundai Palisade (first generation), front three-quarter (its plate is already blacked out in the photograph)'),
    'car-hyundai-santa-fe-white': dict(src='popular2-hyundai-santa-fe-1.jpg', floor=None, plates=[[195, 725, 445, 825]],
        subject='a white Hyundai Santa Fe (fifth generation, 2024-), front three-quarter'),
    'car-hyundai-santa-fe-white-rear': dict(src='popular2-hyundai-santa-fe-2.jpg', floor=None, plates=[[1565, 695, 1770, 790]],
        subject='a white Hyundai Santa Fe (fifth generation, 2024-), rear three-quarter'),
    'car-infiniti-qx60-bronze': dict(src='popular2-infiniti-qx60-1.jpg', floor=None, plates=[],
        subject='a bronze Infiniti QX60 (second generation), front three-quarter (showroom, no plate)'),
    'car-jeep-compass-silver': dict(src='popular2-jeep-compass-1.jpg', floor=None, plates=[[160, 692, 430, 808]],
        subject='a silver Jeep Compass (2021 facelift) S, front three-quarter'),
    'car-jeep-compass-silver-rear': dict(src='popular2-jeep-compass-2.jpg', floor=None, plates=[[1455, 488, 1705, 600]],
        subject='a silver Jeep Compass 4xe (2021 facelift) S, rear three-quarter'),
    'car-jeep-wagoneer-classic-red': dict(src='popular2-jeep-wagoneer-2.jpg', floor=None, plates=[[1230, 860, 1450, 965]],
        subject='a red Jeep Wagoneer (SJ, 1960s-70s), front three-quarter'),
    'car-jeep-wagoneer-classic-red-rear': dict(src='popular2-jeep-wagoneer-3.jpg', floor=None, plates=[[1505, 780, 1635, 865]],
        subject='a red Jeep Wagoneer (SJ, 1960s-70s), rear three-quarter'),
    'car-kia-ev6-gt-black-rear': dict(src='popular2-kia-ev6-1.jpg', floor=None, plates=[[1545, 555, 1770, 655]],
        erase=[[1240, 80, 1335, 114]],
        subject='a black Kia EV6 GT, rear three-quarter'),
    'car-kia-ev6-gt-black': dict(src='popular2-kia-ev6-2.jpg', floor=None, plates=[[1570, 590, 1785, 692]],
        subject='a black Kia EV6 GT, front three-quarter'),
    'car-kia-ev9-silver': dict(src='popular2-kia-ev9-1.jpg', floor=None, plates=[[170, 712, 415, 825]],
        subject='a silver Kia EV9, front three-quarter'),
    'car-kia-sorento-grey': dict(src='popular2-kia-sorento-1.jpg', floor=None, plates=[[155, 712, 390, 850]],
        subject='a grey Kia Sorento (2024 facelift), front three-quarter'),
    'car-kia-soul-green': dict(src='popular2-kia-soul-3.jpg', floor=None, plates=[[1695, 1035, 1820, 1195]],
        subject='a green Kia Soul (third generation), front three-quarter'),
    'car-kia-sportage-black': dict(src='popular2-kia-sportage-1.jpg', floor=None, plates=[[1370, 780, 1685, 905]],
        subject='a black Kia Sportage (fifth generation), front three-quarter'),
    'car-lamborghini-aventador-s-red': dict(src='popular2-lamborghini-aventador-1.jpg', floor=None, plates=[],
        subject='a red Lamborghini Aventador S, front three-quarter (motor show, no plate)'),
    'car-lamborghini-aventador-ultimae-orange': dict(src='popular2-lamborghini-aventador-2.jpg', floor=None, plates=[[1735, 830, 1830, 905]],
        subject='an orange Lamborghini Aventador LP 780-4 Ultimae, doors up, side three-quarter'),
    'car-lamborghini-aventador-roadster-blue-rear': dict(src='popular2-lamborghini-aventador-3.jpg', floor=None, plates=[],
        subject='a blue Lamborghini Aventador S Roadster, rear three-quarter (motor show placard)'),
    'car-lamborghini-huracan-performante-rear': dict(src='popular2-lamborghini-huracan-1.jpg', floor=None, plates=[],
        subject='a white and black Lamborghini Huracan Performante Spyder, rear three-quarter (motor show placard)'),
    'car-lamborghini-huracan-tecnica-blue': dict(src='popular2-lamborghini-huracan-2.jpg', floor=None, plates=[],
        subject='a blue Lamborghini Huracan Tecnica, front three-quarter (no plate on it)'),
    'car-lamborghini-huracan-tecnica-blue-rear': dict(src='popular2-lamborghini-huracan-3.jpg', floor=None, plates=[],
        subject='a blue Lamborghini Huracan Tecnica, rear three-quarter (no plate on it)'),
    'car-land-rover-defender-110-classic-grey-rear': dict(src='popular2-land-rover-defender-110-1.jpg', floor=None, plates=[[140, 650, 235, 800]],
        subject='a grey Land Rover Defender 110 Station Wagon (classic, 2007-16), rear three-quarter'),
    'car-land-rover-defender-110-classic-grey': dict(src='popular2-land-rover-defender-110-2.jpg', floor=None, plates=[[1410, 855, 1610, 945]],
        subject='a grey Land Rover Defender 110 Station Wagon (classic, 2007-16), front three-quarter'),
    'car-lexus-es-white': dict(src='popular2-lexus-es-1.jpg', floor=None, plates=[[175, 625, 435, 730]],
        subject='a white Lexus ES 350 F Sport (seventh generation), front three-quarter'),
    'car-lexus-es-white-rear': dict(src='popular2-lexus-es-2.jpg', floor=None, plates=[[230, 465, 530, 592]],
        subject='a white Lexus ES 350 F Sport (seventh generation), rear three-quarter'),
    'car-lexus-lx-black': dict(src='popular2-lexus-lx-1.jpg', floor=None, plates=[[180, 660, 400, 770]],
        subject='a black Lexus LX 570 (2016 facelift), front three-quarter'),
    'car-lexus-nx-silver-rear': dict(src='popular2-lexus-nx-3.jpg', floor=None, plates=[[1320, 562, 1665, 705]],
        subject='a silver Lexus NX 450h+ (second generation), rear three-quarter'),
    'car-lincoln-aviator-black-rear': dict(src='popular2-lincoln-aviator-2.jpg', floor=None, plates=[[1385, 492, 1610, 602], [1265, 630, 1410, 680]],
        subject='a black Lincoln Aviator (second generation), rear three-quarter'),
    'car-lincoln-aviator-black': dict(src='popular2-lincoln-aviator-3.jpg', floor=None, plates=[[1010, 790, 1285, 895]],
        subject='a black Lincoln Aviator (second generation), front three-quarter'),
    'car-lincoln-navigator-white': dict(src='popular2-lincoln-navigator-3.jpg', floor=None, plates=[[210, 685, 350, 775]],
        subject='a white Lincoln Navigator L (fourth generation), front three-quarter'),
    'car-lucid-air-white-rear': dict(src='popular2-lucid-air-2.jpg', floor=None, plates=[[220, 585, 510, 700]],
        subject='a white Lucid Air sedan, rear three-quarter'),
    'car-lucid-air-white': dict(src='popular2-lucid-air-3.jpg', floor=None, plates=[[1480, 718, 1750, 828]],
        subject='a white Lucid Air sedan, front three-quarter'),
    'car-maserati-mc20-white': dict(src='popular2-maserati-mc20-1.jpg', floor=None, plates=[],
        subject='a white Maserati MC20, front three-quarter (showroom, no plate)'),
    'car-maserati-mc20-cielo-rear': dict(src='popular2-maserati-mc20-2.jpg', floor=None, plates=[[160, 450, 395, 565]],
        subject='a pale grey Maserati MC20 Cielo, rear three-quarter'),
    'car-mazda-cx90-blue': dict(src='popular2-mazda-cx-90-2.jpg', floor=None, plates=[[135, 580, 245, 672]],
        subject='a dark blue Mazda CX-90, front three-quarter'),
    'car-mazda3-hatch-silver-rear': dict(src='popular2-mazda3-1.jpg', floor=None, plates=[[110, 462, 255, 575]],
        subject='a silver Mazda3 hatchback (fourth generation), rear three-quarter'),
    'car-mazda3-hatch-white': dict(src='popular2-mazda3-2.jpg', floor=None, plates=[[1615, 592, 1815, 690]],
        subject='a white Mazda3 hatchback (fourth generation), front three-quarter'),
    'car-mclaren-720s-silver': dict(src='popular2-mclaren-720s-2.jpg', floor=None, plates=[],
        subject='a silver McLaren 720S, front three-quarter (show placard, no plate)'),
    'car-mclaren-720s-grey': dict(src='popular2-mclaren-720s-3.jpg', floor=None, plates=[[1555, 752, 1785, 848]],
        subject='a grey McLaren 720S, front three-quarter'),
    'car-mercedes-amg-gt63-4door-white': dict(src='popular2-mercedes-amg-gt-2.jpg', floor=None, plates=[[1520, 685, 1750, 790]],
        subject='a white Mercedes-AMG GT 63 S E Performance 4-door coupe, front three-quarter'),
    'car-mercedes-amg-gt-black-series-orange': dict(src='popular2-mercedes-amg-gt-3.jpg', floor=None, plates=[[240, 908, 535, 1020]],
        subject='an orange Mercedes-AMG GT Black Series, front three-quarter'),
    'car-mercedes-c-class-all-terrain-white': dict(src='popular2-mercedes-benz-c-class-3.jpg', floor=None, plates=[[1145, 925, 1535, 1020]],
        subject='a white Mercedes-Benz C-Class All-Terrain (W206), front three-quarter'),
    'car-mercedes-w114-classic-cream': dict(src='popular2-mercedes-benz-e-class-1.jpg', floor=None, plates=[[1410, 745, 1675, 840]],
        subject='a cream Mercedes-Benz 240 D (W115, 1970s) with a roof rack, front three-quarter'),
    'car-mercedes-glc-blue': dict(src='popular2-mercedes-benz-glc-3.jpg', floor=None, plates=[[160, 598, 380, 688]],
        subject='a blue Mercedes-Benz GLC (X253), front three-quarter'),
    'car-mini-classic-cream': dict(src='popular2-mini-cooper-1.jpg', floor=None, plates=[[205, 900, 505, 1048]],
        subject='a cream classic Mini (Morris Mini-Minor, 1960s), front three-quarter'),
    'car-nissan-altima-silver-rear': dict(src='popular2-nissan-altima-2.jpg', floor=None, plates=[[1385, 435, 1665, 548]],
        subject='a silver Nissan Altima (sixth generation) SR, rear three-quarter'),
    'car-nissan-gtr-r35-white': dict(src='popular2-nissan-gt-r-3.jpg', floor=None, plates=[[1420, 630, 1665, 735]],
        subject='a white Nissan GT-R (R35), front three-quarter'),
    'car-nissan-pathfinder-rock-creek-rear': dict(src='popular2-nissan-pathfinder-1.jpg', floor=None, plates=[[155, 712, 445, 860]],
        subject='a sand Nissan Pathfinder Rock Creek (fifth generation), rear three-quarter'),
    'car-nissan-titan-xd-silver': dict(src='popular2-nissan-titan-1.jpg', floor=None, plates=[],
        subject='a silver Nissan Titan XD crew cab pickup, front three-quarter (no plate on it)'),
    'car-nissan-z-yellow': dict(src='popular2-nissan-z-1.jpg', floor=None, plates=[],
        subject='a yellow Nissan Z (Fairlady Z, 2023-), front three-quarter (showroom, no plate)'),
    'car-polestar-2-white': dict(src='popular2-polestar-2-1.jpg', floor=None, plates=[],
        subject='a white Polestar 2, front three-quarter (showroom, no plate)'),
    'car-polestar-2-grey': dict(src='popular2-polestar-2-3.jpg', floor=None, plates=[[1530, 648, 1765, 736]],
        subject='a grey Polestar 2, front three-quarter'),
    'car-porsche-cayenne-gts-coupe-white-rear': dict(src='popular2-porsche-cayenne-1.jpg', floor=None, plates=[[205, 655, 465, 770]],
        subject='a chalk Porsche Cayenne GTS Coupe (third generation), rear three-quarter'),
    'car-porsche-cayenne-gts-white-rear': dict(src='popular2-porsche-cayenne-2.jpg', floor=None, plates=[[1250, 595, 1605, 730]],
        subject='a chalk Porsche Cayenne GTS (third generation), rear three-quarter'),
    'car-porsche-cayenne-gts-silver': dict(src='popular2-porsche-cayenne-3.jpg', floor=None, plates=[[1560, 685, 1845, 790]],
        subject='a silver Porsche Cayenne GTS (third generation, 2024 facelift), front three-quarter'),
    'car-porsche-macan-white': dict(src='popular2-porsche-macan-3.jpg', floor=None, plates=[[180, 780, 435, 880]],
        subject='a white Porsche Macan (2022 facelift), front three-quarter'),
    'car-porsche-panamera-turbo-bronze': dict(src='popular2-porsche-panamera-1.jpg', floor=None, plates=[[1600, 805, 1850, 915]],
        subject='a bronze Porsche Panamera Turbo E-Hybrid (third generation), front three-quarter'),
    'car-porsche-panamera-gts-chalk': dict(src='popular2-porsche-panamera-2.jpg', floor=None, plates=[[165, 590, 405, 670]],
        subject='a chalk Porsche Panamera GTS (second generation), front three-quarter'),
    'car-porsche-panamera-turbo-chalk-rear': dict(src='popular2-porsche-panamera-3.jpg', floor=None, plates=[[1530, 455, 1745, 535]],
        subject='a chalk Porsche Panamera Turbo (second generation), rear three-quarter'),
    'car-porsche-taycan-gts-sport-turismo-rear': dict(src='popular2-porsche-taycan-1.jpg', floor=None, plates=[],
        subject='a chalk Porsche Taycan GTS Sport Turismo, rear three-quarter (no plate on it)'),
    'car-range-rover-sport-grey': dict(src='popular2-range-rover-sport-1.jpg', floor=None, plates=[[180, 778, 415, 870]],
        subject='a grey Range Rover Sport (third generation, 2022-), front three-quarter'),
    'car-rolls-royce-ghost-purple-side': dict(src='popular2-rolls-royce-ghost-2.jpg', floor=None, plates=[],
        subject='a purple-grey Rolls-Royce Ghost (second generation), side on (no plate in view)'),
    'car-subaru-crosstrek-wilderness-blue': dict(src='popular2-subaru-crosstrek-1.jpg', floor=None, plates=[[1530, 685, 1755, 770]],
        subject='a blue Subaru Crosstrek (third generation) with gold trim, front three-quarter'),
    'car-subaru-crosstrek-wilderness-blue-rear': dict(src='popular2-subaru-crosstrek-2.jpg', floor=None, plates=[[155, 425, 325, 505]],
        subject='a blue Subaru Crosstrek (third generation) with gold trim, rear three-quarter'),
    'car-subaru-wrx-blue': dict(src='popular2-subaru-wrx-3.jpg', floor=None, plates=[[1355, 790, 1680, 945]],
        subject='a blue Subaru WRX (fifth generation), front three-quarter'),
    'car-subaru-impreza-wrx-1992-silver': dict(src='popular2-subaru-wrx-2.jpg', floor=None, plates=[],
        subject='a silver Subaru Impreza WRX (first generation, 1992), front three-quarter (museum placard, no plate)'),
    'car-toyota-gr86-blue': dict(src='popular2-toyota-gr86-2.jpg', floor=None, plates=[[125, 630, 345, 740]],
        subject='a blue Toyota GR86, front three-quarter'),
    'car-toyota-venza-silver': dict(src='popular2-toyota-venza-1.jpg', floor=None, plates=[],
        subject='a silver Toyota Venza (Harrier, fourth generation), front three-quarter (no plate on it)'),
    'car-toyota-venza-silver-rear': dict(src='popular2-toyota-venza-2.jpg', floor=None, plates=[],
        subject='a silver Toyota Venza (Harrier, fourth generation), rear three-quarter (no plate on it)'),
    'car-vw-atlas-silver': dict(src='popular2-volkswagen-atlas-1.jpg', floor=None, plates=[[1395, 812, 1685, 958]],
        subject='a silver Volkswagen Atlas (2021 facelift), front three-quarter'),
    'car-vw-golf-gti-tcr-white-rear': dict(src='popular2-volkswagen-golf-gti-1.jpg', floor=None, plates=[[1440, 672, 1700, 762]],
        subject='a white Volkswagen Golf GTI TCR (Mk7.5), rear three-quarter'),
    'car-vw-golf-gti-clubsport-grey': dict(src='popular2-volkswagen-golf-gti-2.jpg', floor=None, plates=[[1480, 640, 1735, 722]],
        subject='a grey Volkswagen Golf GTI Clubsport (Mk8), front three-quarter'),
    'car-vw-golf-mk1-white-rear': dict(src='popular2-volkswagen-golf-gti-3.jpg', floor=None, plates=[[1520, 615, 1710, 770]],
        subject='a white Volkswagen Golf Mk1 with gold BBS wheels, rear three-quarter'),
    'car-vw-id5-gtx-silver': dict(src='popular2-volkswagen-id-4-1.jpg', floor=None, plates=[[1440, 715, 1700, 805]],
        subject='a silver Volkswagen ID.5 GTX, front three-quarter'),
    'car-vw-jetta-gli-grey': dict(src='popular2-volkswagen-jetta-2.jpg', floor=None, plates=[[310, 805, 705, 940]],
        subject='a grey Volkswagen Jetta GLI (seventh generation), front three-quarter'),
    'car-vw-tiguan-2024-red': dict(src='popular2-volkswagen-tiguan-1.jpg', floor=None, plates=[[1505, 765, 1745, 870]],
        subject='a red Volkswagen Tiguan (third generation, 2024-) R-Line, front three-quarter'),
    'car-volvo-xc60-silver-rear': dict(src='popular2-volvo-xc60-1.jpg', floor=None, plates=[[1205, 595, 1555, 700]],
        subject='a silver Volvo XC60 B5 (second generation, 2021 facelift), rear three-quarter'),
    'car-volvo-xc60-silver': dict(src='popular2-volvo-xc60-2.jpg', floor=None, plates=[[1500, 725, 1735, 835]],
        subject='a silver Volvo XC60 (second generation, 2021 facelift), front three-quarter'),
    'car-volvo-xc90-silver-rear': dict(src='popular2-volvo-xc90-1.jpg', floor=None, plates=[[250, 495, 525, 595]],
        subject='a silver Volvo XC90 B5 (second generation), rear three-quarter'),
    'car-volvo-xc90-2025-white': dict(src='popular2-volvo-xc90-2.jpg', floor=None, plates=[[175, 795, 470, 915]],
        subject='a white Volvo XC90 (2025 facelift), front three-quarter'),
    # 2026-10-04 (owner: "more variety?": car colours): the colours fetch, two photographs
    # each of 20 popular models in red, blue, black and grey
    'car-chevy-corvette-c1-blue': dict(src='colours-chevrolet-corvette-blue-1.jpg', floor=None, plates=[[1605, 872, 1725, 968]],
        subject='a blue Chevrolet Corvette C1 (1961-62) roadster, front three-quarter'),
    'car-chevy-corvette-c3-grey-rear': dict(src='colours-chevrolet-corvette-grey-2.jpg', floor=None, plates=[[1335, 905, 1465, 975]],
        subject='a dark grey Chevrolet Corvette C3 (1970s) coupe, rear three-quarter'),
    'car-chevy-corvette-c8-red': dict(src='colours-chevrolet-corvette-red-1.jpg', floor=None, plates=[],
        subject='a red Chevrolet Corvette Stingray (C8) at a show, front three-quarter (no plate)'),
    'car-chevy-silverado-z71-black': dict(src='colours-chevrolet-silverado-black-2.jpg', floor=None, plates=[],
        subject='a black Chevrolet Silverado 1500 Z71 (2016-18), front three-quarter (no front plate)'),
    'car-ford-bronco-sport-black-rear': dict(src='colours-ford-bronco-black-1.jpg', floor=None, plates=[[1495, 775, 1715, 865]],
        subject='a black Ford Bronco Sport, rear three-quarter'),
    'car-ford-bronco-black-diamond-silver': dict(src='colours-ford-bronco-black-2.jpg', floor=None, plates=[],
        subject='a silver Ford Bronco Black Diamond four-door (2023), front three-quarter (no front plate)'),
    'car-ford-bronco-sport-badlands-blue': dict(src='colours-ford-bronco-blue-1.jpg', floor=None, plates=[[1500, 815, 1710, 965]],
        subject='an Area 51 blue Ford Bronco Sport Badlands, front three-quarter'),
    'car-ford-bronco-sport-heritage-blue': dict(src='colours-ford-bronco-grey-1.jpg', floor=None, plates=[],
        subject='a blue-grey Ford Bronco Sport Heritage with a white roof, front three-quarter (no front plate)'),
    'car-ford-bronco-sport-badlands-red': dict(src='colours-ford-bronco-red-1.jpg', floor=None, plates=[[250, 805, 550, 940]],
        subject='a red Ford Bronco Sport Badlands, front three-quarter'),
    'car-ford-f150-grey': dict(src='colours-ford-f-150-grey-1.jpg', floor=None, plates=[[180, 755, 430, 855]],
        subject='a grey Ford F-150 (fourteenth generation, 2021-) SuperCrew, front three-quarter'),
    'car-ford-mustang-convertible-grey': dict(src='colours-ford-mustang-grey-1.jpg', floor=None, plates=[[160, 720, 410, 830]],
        subject='a grey Ford Mustang GT Convertible (seventh generation, 2024-), front three-quarter'),
    'car-ford-mustang-gt-blue-grey': dict(src='colours-ford-mustang-grey-2.jpg', floor=None, plates=[],
        subject='a blue-grey Ford Mustang GT (seventh generation, 2024-), front three-quarter (no front plate)'),
    'car-honda-civic-type-r-fk8-blue-rear': dict(src='colours-honda-civic-blue-1.jpg', floor=None, plates=[[380, 455, 610, 555]],
        subject='a blue Honda Civic Type R (FK8), rear three-quarter'),
    'car-honda-civic-sedan-blue-rear': dict(src='colours-honda-civic-blue-2.jpg', floor=None, plates=[[1395, 540, 1665, 635]],
        subject='a blue Honda Civic Sport sedan (eleventh generation), rear three-quarter'),
    'car-honda-crv-2023-black': dict(src='colours-honda-cr-v-black-1.jpg', floor=None, plates=[[1310, 900, 1600, 1015]],
        subject='a black Honda CR-V (sixth generation, 2023-), front three-quarter'),
    'car-honda-crv-2023-blue': dict(src='colours-honda-cr-v-blue-1.jpg', floor=None, plates=[[180, 722, 420, 800]],
        subject='a dark blue Honda CR-V (sixth generation, 2023-), front three-quarter'),
    'car-jeep-wrangler-2door-black-rear': dict(src='colours-jeep-wrangler-black-2.jpg', floor=None, plates=[[380, 1030, 690, 1115]],
        subject='a black Jeep Wrangler two-door (JL), rear three-quarter'),
    'car-jeep-wrangler-sahara-red': dict(src='colours-jeep-wrangler-red-1.jpg', floor=None, plates=[[290, 812, 490, 895]],
        subject='a red Jeep Wrangler Unlimited (JL) with a soft top, front three-quarter'),
    'car-mercedes-amg-g63-2025-black': dict(src='colours-mercedes-amg-g-63-black-1.jpg', floor=None, plates=[[440, 932, 810, 1025]],
        subject='a black Mercedes-AMG G 63 (W465, 2024-), front three-quarter'),
    'car-mercedes-amg-g63-4x4-blue-rear': dict(src='colours-mercedes-amg-g-63-blue-1.jpg', floor=None, plates=[[1270, 792, 1500, 868]],
        subject='a blue Mercedes-AMG G 63 4x4 squared with a roof rack, rear three-quarter'),
    'car-mercedes-amg-g63-cabriolet-blue': dict(src='colours-mercedes-amg-g-63-blue-2.jpg', floor=None, plates=[[245, 745, 405, 845]],
        subject='a blue Mercedes-AMG G 63 cabriolet conversion with red seats, front three-quarter'),
    'car-mercedes-amg-g63-silver-rear': dict(src='colours-mercedes-amg-g-63-grey-1.jpg', floor=None, plates=[[1460, 845, 1660, 905]],
        subject='a silver Mercedes-AMG G 63 (W463), rear three-quarter'),
    'car-ram-1500-rebel-black': dict(src='colours-ram-1500-black-1.jpg', floor=None, plates=[[380, 822, 590, 895]],
        subject='a black Ram 1500 Rebel (fifth generation), front three-quarter'),
    'car-ram-1500-limited-grey': dict(src='colours-ram-1500-grey-1.jpg', floor=None, plates=[[1620, 905, 1690, 990]],
        subject='a grey Ram 1500 Limited (fifth generation), front three-quarter'),
    'car-ram-trx-red': dict(src='colours-ram-1500-red-1.jpg', floor=None, plates=[[270, 895, 580, 990]],
        subject='a red Ram 1500 TRX, front three-quarter'),
    'car-tesla-model-y-juniper-grey': dict(src='colours-tesla-model-3-grey-2.jpg', floor=None, plates=[[290, 935, 530, 1025]],
        subject='a Stealth Grey Tesla Model Y (2025 Juniper), front three-quarter'),
    'car-tesla-model-3-highland-red': dict(src='colours-tesla-model-3-red-1.jpg', floor=None, plates=[[1430, 870, 1730, 985]],
        subject='an Ultra Red Tesla Model 3 (2024 Highland), front three-quarter'),
    'car-tesla-model-y-black-side': dict(src='colours-tesla-model-y-black-1.jpg', floor=None, plates=[[1730, 840, 1860, 935]],
        subject='a black Tesla Model Y, side three-quarter'),
    'car-tesla-model-y-blue': dict(src='colours-tesla-model-y-blue-2.jpg', floor=None, plates=[[1700, 930, 1850, 1020]],
        subject='a Deep Blue Tesla Model Y, front three-quarter'),
    'car-tesla-model-y-performance-red': dict(src='colours-tesla-model-y-red-1.jpg', floor=None, plates=[[150, 700, 370, 805]],
        subject='an Ultra Red Tesla Model Y Performance (2025), front three-quarter'),
    'car-toyota-4runner-limited-black': dict(src='colours-toyota-4runner-black-1.jpg', floor=None, plates=[[90, 872, 220, 958]],
        subject='a black Toyota 4Runner (fifth generation), front three-quarter'),
    'car-toyota-highlander-black': dict(src='colours-toyota-highlander-black-1.jpg', floor=None, plates=[[300, 880, 570, 965]],
        subject='a black Toyota Highlander (XU70), front three-quarter'),
    'car-toyota-highlander-blue': dict(src='colours-toyota-highlander-blue-1.jpg', floor=None, plates=[[1470, 590, 1670, 688]],
        subject='a dark blue Toyota Highlander (XU70), front three-quarter'),
    'car-toyota-highlander-red': dict(src='colours-toyota-highlander-red-1.jpg', floor=None, plates=[[210, 700, 445, 790]],
        subject='a red Toyota Highlander Hybrid (XU70), front three-quarter'),
    'car-toyota-rav4-2025-black': dict(src='colours-toyota-rav4-black-1.jpg', floor=None, plates=[[205, 580, 310, 680]],
        subject='a black Toyota RAV4 Hybrid Z (sixth generation, 2025), front three-quarter'),
    'car-toyota-rav4-phev-red-rear': dict(src='colours-toyota-rav4-red-1.jpg', floor=None, plates=[[1150, 595, 1530, 700]],
        subject='a red Toyota RAV4 Plug-in Hybrid GR Sport (fifth generation), rear'),
    'car-toyota-rav4-phev-red': dict(src='colours-toyota-rav4-red-2.jpg', floor=None, plates=[[185, 770, 430, 875]],
        subject='a red Toyota RAV4 Plug-in Hybrid GR Sport (fifth generation), front three-quarter'),
    'car-toyota-tacoma-trd-offroad-black': dict(src='colours-toyota-tacoma-black-1.jpg', floor=None, plates=[[110, 610, 320, 690]],
        subject='a black Toyota Tacoma TRD Off-Road (third generation), front three-quarter'),
    'car-toyota-tacoma-trd-black': dict(src='colours-toyota-tacoma-black-2.jpg', floor=None, plates=[[315, 820, 670, 935]],
        subject='a black Toyota Tacoma TRD Off-Road (third generation), front three-quarter, close'),
    'car-toyota-tacoma-trd-sport-blue': dict(src='colours-toyota-tacoma-blue-2.jpg', floor=None, plates=[[1470, 690, 1630, 770]],
        subject='a blue Toyota Tacoma TRD Sport (third generation) with a bed cap, front three-quarter'),
    'car-toyota-tacoma-trd-offroad-red': dict(src='colours-toyota-tacoma-red-1.jpg', floor=None, plates=[[180, 790, 440, 875]],
        subject='a red Toyota Tacoma TRD Off-Road (third generation), front three-quarter'),
    'car-toyota-tundra-1794-black': dict(src='colours-toyota-tundra-black-1.jpg', floor=None, plates=[[1540, 870, 1640, 950]],
        subject='a black Toyota Tundra 1794 Edition (second generation), front three-quarter'),
    'car-toyota-tundra-trd-pro-orange-rear': dict(src='colours-toyota-tundra-red-1.jpg', floor=None, plates=[[1540, 630, 1660, 740]],
        subject='a Solar Octane Toyota Tundra TRD Pro (third generation) at a show, rear three-quarter'),
    # 2026-10-04 (owner: "more variety?": other buy categories, same real-photo treatment):
    # gold, silver, coins, a graded card, consoles, audio, cameras and watches photographed on
    # Commons; keep='all' keeps every separate piece (coin pairs, sets), not only the biggest
    'photo-gold-bracelet-filigree': dict(src='gold-gold-bracelet-1.jpg', floor=None, plates=[],
        subject='a gold filigree cuff bracelet'),
    'photo-gold-bracelet-flat': dict(src='gold-gold-bracelet-4.jpg', floor=None, plates=[],
        subject='a flat gold link bracelet, laid out'),
    'photo-gold-bars-pair': dict(src='gold-gold-bullion-bar-2.jpg', floor=None, plates=[], keep='all',
        subject='two gold bullion bars, crossed'),
    'photo-gold-bars-pamp': dict(src='gold-gold-bullion-bar-3.jpg', floor=None, plates=[], keep='all',
        subject='a PAMP Suisse gold bar and a small cast gold bar'),
    'photo-gold-chain-chunky': dict(src='gold-gold-chain-necklace-1.jpg', floor=None, plates=[],
        subject='a heavy gold link chain necklace'),
    'photo-gold-eagle-coins': dict(src='gold-gold-coin-american-eagle-1.jpg', floor=None, plates=[], keep='all',
        subject='two gold coins, an American Gold Eagle and a Liberty double eagle'),
    'photo-gold-double-eagle-1907': dict(src='gold-gold-coin-american-eagle-3.jpg', floor=None, plates=[],
        subject='a 1907 Saint-Gaudens gold double eagle ($20)'),
    'photo-gold-eagle-proof': dict(src='gold-gold-coin-american-eagle-4.jpg', floor=None, plates=[],
        subject='a 2006 American Gold Eagle proof coin'),
    'photo-gold-krugerrand-obverse': dict(src='gold-gold-krugerrand-1.jpg', floor=None, plates=[],
        subject='a gold Krugerrand (obverse, Paul Kruger)'),
    'photo-gold-krugerrand-springbok': dict(src='gold-gold-krugerrand-2.jpg', floor=None, plates=[],
        subject='a 2017 gold Krugerrand (reverse, springbok)'),
    'photo-gold-krugerrands-pair': dict(src='gold-gold-krugerrand-3.jpg', floor=None, plates=[], keep='all',
        subject='two gold Krugerrands'),
    'photo-gold-nugget': dict(src='gold-gold-nugget-3.jpg', floor=None, plates=[],
        subject='a large natural gold nugget'),
    'photo-gold-pocket-watch': dict(src='gold-gold-watch-1.jpg', floor=None, plates=[],
        subject='a gold pocket watch on its chain'),
    'photo-gold-rings-pink': dict(src='gold-gold-jewelry-rings-3.jpg', floor=None, plates=[], keep='all',
        subject='three gold rings set with synthetic rubies (Soviet, red gold)'),
    'photo-silver-eagle-obverse': dict(src='silver-american-silver-eagle-2.jpg', floor=None, plates=[],
        subject='a 2014 American Silver Eagle proof (obverse)'),
    'photo-silver-eagle-reverse': dict(src='silver-american-silver-eagle-4.jpg', floor=None, plates=[],
        subject='an American Silver Eagle proof (reverse)'),
    'photo-silver-morgan-1886': dict(src='silver-morgan-silver-dollar-3.jpg', floor=None, plates=[],
        subject='an 1886 Morgan silver dollar'),
    'photo-silver-peace-dollar-pair': dict(src='silver-peace-dollar-1.jpg', floor=None, plates=[], keep='all',
        subject='a 1921 Peace silver dollar, obverse and reverse'),
    'photo-silver-peace-dollar': dict(src='silver-peace-dollar-2.jpg', floor=None, plates=[],
        subject='a 1964 Peace dollar'),
    'photo-silver-bar-poured': dict(src='silver-silver-bullion-bar-3.jpg', floor=None, plates=[],
        subject='a poured silver bullion bar'),
    'photo-silver-maple-stack': dict(src='silver-silver-maple-leaf-coin-2.jpg', floor=None, plates=[],
        subject='a stack of silver Maple Leaf coins'),
    'photo-silver-maple-pile': dict(src='silver-silver-maple-leaf-coin-3.jpg', floor=None, plates=[], keep='all',
        subject='a pile of silver Maple Leaf coins'),
    'photo-silver-tea-set-dark': dict(src='silver-silver-tea-set-3.jpg', floor=None, plates=[],
        subject='a sterling silver tea and coffee service on a gallery tray'),
    'photo-silver-tea-set-white': dict(src='silver-silver-tea-set-4.jpg', floor=None, plates=[],
        subject='a modern silver tea set on a tray'),
    'photo-silver-tea-set-tray': dict(src='silver-silver-tea-set-2.jpg', floor=None, plates=[],
        subject='a silver tea and coffee service on a tray'),
    'photo-coin-gold-eagle-obverse': dict(src='coins-american-gold-eagle-coin-1.jpg', floor=None, plates=[],
        subject='a 2013 American Gold Eagle proof (obverse)'),
    'photo-coin-gold-eagle-reverse': dict(src='coins-american-gold-eagle-coin-2.jpg', floor=None, plates=[],
        subject='an American Gold Eagle proof (reverse)'),
    'photo-coin-buffalo-nickel-pair': dict(src='coins-buffalo-nickel-1.jpg', floor=None, plates=[], keep='all',
        subject='a Buffalo nickel, obverse and reverse'),
    'photo-coin-buffalo-nickel-stack': dict(src='coins-buffalo-nickel-2.jpg', floor=None, plates=[],
        subject='a stack of Buffalo nickels'),
    'photo-coin-indian-cent-pair': dict(src='coins-indian-head-cent-1.jpg', floor=None, plates=[], keep='all',
        subject='an 1859 Indian Head cent, obverse and reverse'),
    'photo-coin-indian-cent-1860': dict(src='coins-indian-head-cent-4.jpg', floor=None, plates=[],
        subject='an 1860 Indian Head cent'),
    'photo-coin-double-eagle-1849': dict(src='coins-liberty-head-double-eagle-1.jpg', floor=None, plates=[], keep='all',
        subject='an 1849 Liberty Head double eagle, obverse and reverse'),
    'photo-coin-double-eagle-1866': dict(src='coins-liberty-head-double-eagle-3.jpg', floor=None, plates=[], keep='all',
        subject='an 1866 Liberty Head double eagle, obverse and reverse'),
    'photo-coin-wheat-cent': dict(src='coins-lincoln-wheat-penny-3.jpg', floor=None, plates=[],
        subject='a Lincoln wheat cent (reverse)'),
    'photo-coin-wheat-cent-1944': dict(src='coins-lincoln-wheat-penny-4.jpg', floor=None, plates=[],
        subject='a 1944 Lincoln wheat cent'),
    'photo-coin-mercury-dime': dict(src='coins-mercury-dime-1.jpg', floor=None, plates=[],
        subject='a 1943 Mercury dime (obverse)'),
    'photo-coin-mercury-dime-reverse': dict(src='coins-mercury-dime-2.jpg', floor=None, plates=[],
        subject='a Mercury dime (reverse)'),
    'photo-coin-morgan-dollar': dict(src='coins-morgan-dollar-1.jpg', floor=None, plates=[],
        subject='an 1880 Morgan dollar (obverse)'),
    'photo-coin-morgan-dollar-reverse': dict(src='coins-morgan-dollar-2.jpg', floor=None, plates=[],
        subject='a Morgan dollar (reverse)'),
    'photo-coin-ngc-peace-dollar': dict(src='coins-ngc-graded-coin-1.jpg', floor=None, plates=[],
        subject='a 1922 Peace dollar graded MS 63 in an NGC slab'),
    'photo-coin-ngc-morgan-dollar': dict(src='coins-ngc-graded-coin-2.jpg', floor=None, plates=[],
        subject='an 1881-S Morgan dollar graded MS 64 in an NGC slab'),
    'photo-coin-ngc-slabs-pair': dict(src='coins-ngc-graded-coin-3.jpg', floor=None, plates=[], keep='all',
        subject='two NGC graded coin slabs, a gold dollar and a Morgan dollar'),
    'photo-coin-pcgs-morgan': dict(src='coins-pcgs-slab-coin-1.jpg', floor=None, plates=[],
        subject='a Morgan dollar in a PCGS slab'),
    'photo-coin-pcgs-falcon': dict(src='coins-pcgs-slab-coin-2.jpg', floor=None, plates=[],
        subject='a 2016 Canadian silver Peregrine Falcon proof coin in its capsule'),
    'photo-coin-pcgs-gold-dollar': dict(src='coins-pcgs-slab-coin-4.jpg', floor=None, plates=[],
        subject='a 1904 gold dollar graded MS 64 in a PCGS slab'),
    'photo-coin-saint-gaudens-pair': dict(src='coins-saint-gaudens-double-eagle-1.jpg', floor=None, plates=[], keep='all',
        subject='a 1907 Saint-Gaudens double eagle, obverse and reverse'),
    'photo-coin-saint-gaudens-1933': dict(src='coins-saint-gaudens-double-eagle-4.jpg', floor=None, plates=[],
        subject='a 1933 Saint-Gaudens double eagle'),
    'photo-coin-walking-liberty-trio': dict(src='coins-walking-liberty-half-dollar-1.jpg', floor=None, plates=[], keep='all',
        subject='three Walking Liberty half dollars'),
    'photo-coin-half-dollar-stacks': dict(src='coins-walking-liberty-half-dollar-2.jpg', floor=None, plates=[], keep='all',
        subject='two stacks of half dollars'),
    'photo-coin-album': dict(src='coins-coin-collection-album-1.jpg', floor=None, plates=[],
        subject='a coin album with a loose collection, rolls and holders'),
    'photo-sports-psa-1952': dict(src='sportsc-baseball-card-1.jpg', floor=None, plates=[],
        subject='a 1952 Laval Dairy baseball card (John Malangone, Three Rivers)'),
    'photo-gaming-dualsense-white': dict(src='gaming-dualsense-controller-1.jpg', floor=None, plates=[],
        subject='a white PlayStation 5 DualSense controller'),
    'photo-gaming-dualsense-black': dict(src='gaming-dualsense-controller-3.jpg', floor=None, plates=[],
        subject='a black PlayStation 5 DualSense controller'),
    'photo-gaming-switch-dock': dict(src='gaming-nintendo-switch-1.jpg', floor=None, plates=[], keep='all',
        subject='a Nintendo Switch: Joy-Con in the grip and the dock'),
    'photo-gaming-switch2-joycon': dict(src='gaming-nintendo-switch-2-1.jpg', floor=None, plates=[], keep='all',
        subject='Nintendo Switch 2 Joy-Con 2 controllers'),
    'photo-gaming-switch2-docked': dict(src='gaming-nintendo-switch-3.jpg', floor=None, plates=[],
        subject='a Nintendo Switch 2 in its dock'),
    'photo-gaming-switch2': dict(src='gaming-nintendo-switch-4.jpg', floor=None, plates=[],
        subject='a Nintendo Switch 2 with Joy-Con 2 attached'),
    'photo-gaming-switch-oled-docked': dict(src='gaming-nintendo-switch-oled-1.jpg', floor=None, plates=[],
        subject='a white Nintendo Switch OLED in its dock'),
    'photo-gaming-switch-oled': dict(src='gaming-nintendo-switch-oled-4.jpg', floor=None, plates=[],
        subject='a white Nintendo Switch OLED with Joy-Con attached'),
    'photo-gaming-switch-oled-set': dict(src='gaming-nintendo-switch-oled-3.jpg', floor=None, plates=[], keep='all',
        subject='a white Nintendo Switch OLED and its dock'),
    'photo-gaming-ps5-black': dict(src='gaming-playstation-5-1.jpg', floor=None, plates=[],
        subject='a PlayStation 5 standing, with a DualSense'),
    'photo-gaming-ps5-white': dict(src='gaming-playstation-5-3.jpg', floor=None, plates=[],
        subject='a PlayStation 5 with a DualSense'),
    'photo-gaming-steam-deck': dict(src='gaming-steam-deck-2.jpg', floor=None, plates=[],
        subject='a Valve Steam Deck'),
    'photo-gaming-xbox-series-x': dict(src='gaming-xbox-series-x-3.jpg', floor=None, plates=[],
        subject='an Xbox Series X with a controller'),
    'photo-audio-airpods': dict(src='audio-airpods-4-1.jpg', floor=None, plates=[], keep='all',
        subject='AirPods (second generation) and their case'),
    'photo-audio-airpods-max-blue': dict(src='audio-airpods-4-2.jpg', floor=None, plates=[],
        subject='AirPods Max in blue'),
    'photo-audio-airpods-max-silver': dict(src='audio-airpods-4-4.jpg', floor=None, plates=[],
        subject='AirPods Max in silver'),
    'photo-audio-airpods-max-case': dict(src='audio-airpods-max-1.jpg', floor=None, plates=[],
        subject='AirPods Max in the Smart Case'),
    'photo-audio-airpods-max-grey': dict(src='audio-airpods-max-2.jpg', floor=None, plates=[],
        subject='AirPods Max in space grey, ear cups down'),
    'photo-audio-airpods-max-front': dict(src='audio-airpods-max-3.jpg', floor=None, plates=[],
        subject='AirPods Max in space grey, front on'),
    'photo-audio-airpods-pro': dict(src='audio-airpods-pro-1.jpg', floor=None, plates=[], keep='all',
        subject='AirPods Pro (second generation) and their case'),
    'photo-audio-airpods-pro-buds': dict(src='audio-airpods-pro-4.jpg', floor=None, plates=[], keep='all',
        subject='a pair of AirPods Pro'),
    'photo-audio-beats-fit-pro-case': dict(src='audio-beats-fit-pro-1.jpg', floor=None, plates=[],
        subject='the Beats Fit Pro charging case in white'),
    'photo-audio-bose-qc25': dict(src='audio-bose-quietcomfort-headphones-2.jpg', floor=None, plates=[],
        subject='Bose QuietComfort 25 headphones'),
    'photo-audio-jbl-go-red': dict(src='audio-jbl-speaker-2.jpg', floor=None, plates=[],
        subject='a red JBL Go speaker'),
    'photo-audio-jbl-go-red-dark': dict(src='audio-jbl-speaker-4.jpg', floor=None, plates=[],
        subject='a red JBL Go speaker'),
    'photo-audio-galaxy-buds-cases': dict(src='audio-samsung-galaxy-buds-3.jpg', floor=None, plates=[], keep='all',
        subject='two Samsung Galaxy Buds cases, white and black'),
    'photo-audio-sonos-play1': dict(src='audio-sonos-speaker-4.jpg', floor=None, plates=[],
        subject='a white Sonos Play:1 speaker'),
    'photo-camera-canon-100mm': dict(src='cameras-camera-lens-1.jpg', floor=None, plates=[],
        subject='a Canon EF 100mm f/2.8L Macro lens'),
    'photo-camera-canon-5d2': dict(src='cameras-canon-eos-5d-1.jpg', floor=None, plates=[],
        subject='a Canon EOS 5D Mark II with a 50mm lens'),
    'photo-camera-canon-5d2-front': dict(src='cameras-canon-eos-5d-2.jpg', floor=None, plates=[],
        subject='a Canon EOS 5D Mark II with a 50mm lens, front three-quarter'),
    'photo-camera-canon-5d4': dict(src='cameras-canon-eos-5d-3.jpg', floor=None, plates=[],
        subject='a Canon EOS 5D Mark IV body'),
    'photo-camera-canon-r5': dict(src='cameras-canon-eos-r5-1.jpg', floor=None, plates=[],
        subject='a Canon EOS R5 body'),
    'photo-camera-canon-r6': dict(src='cameras-canon-eos-r6-3.jpg', floor=None, plates=[],
        subject='a Canon EOS R6 with an RF lens'),
    'photo-camera-dji-mini-4-pro': dict(src='cameras-dji-mini-4-pro-2.jpg', floor=None, plates=[],
        subject='a DJI Mini 4 Pro drone, arms out'),
    'photo-camera-fujifilm-xt5': dict(src='cameras-fujifilm-x-t5-2.jpg', floor=None, plates=[],
        subject='a silver Fujifilm X-T5 with a zoom lens'),
    'photo-camera-gopro': dict(src='cameras-gopro-hero-1.jpg', floor=None, plates=[],
        subject='a GoPro HERO action camera'),
    'photo-camera-leica-q2': dict(src='cameras-leica-q2-4.jpg', floor=None, plates=[],
        subject='a Leica Q2 with lens hood'),
    'photo-camera-leica-q2-dark': dict(src='cameras-leica-q2-3.jpg', floor=None, plates=[],
        subject='a Leica Q2'),
    'photo-camera-nikon-z8': dict(src='cameras-nikon-z8-3.jpg', floor=None, plates=[],
        subject='a Nikon Z8 with a zoom lens'),
    'photo-camera-sony-a7r-gm': dict(src='cameras-sony-a7r-2.jpg', floor=None, plates=[],
        subject='a Sony a7R with a G Master lens'),
    'photo-camera-sony-a7r5': dict(src='cameras-sony-a7r-3.jpg', floor=None, plates=[],
        subject='a Sony a7R V body'),
    'photo-camera-sony-a7r-body': dict(src='cameras-sony-a7r-4.jpg', floor=None, plates=[],
        subject='a Sony a7R body'),
    'photo-camera-sony-a7iv': dict(src='cameras-sony-alpha-a7-iv-1.jpg', floor=None, plates=[],
        subject='a Sony a7 IV with a zoom lens'),
    'photo-camera-sony-a7iv-zoom': dict(src='cameras-sony-alpha-a7-iv-4.jpg', floor=None, plates=[],
        subject='a Sony a7 IV with a zoom lens, from above'),
    'photo-wear-vision-pro': dict(src='wearables-apple-vision-pro-3.jpg', floor=None, plates=[],
        subject='an Apple Vision Pro with the Solo Knit Band'),
    'photo-wear-watch-s10-pair': dict(src='wearables-apple-watch-series-10-1.jpg', floor=None, plates=[], keep='all',
        subject='two Apple Watch Series 10 with Sport Bands'),
    'photo-wear-watch-s10-milanese': dict(src='wearables-apple-watch-series-10-2.jpg', floor=None, plates=[], keep='all',
        subject='two Apple Watch Series 10 with Milanese Loops'),
    'photo-wear-watch-s10-white': dict(src='wearables-apple-watch-series-10-4.jpg', floor=None, plates=[], keep='all',
        subject='two Apple Watch Series 10 with Sport Bands'),
    'photo-wear-watch-s9-pair': dict(src='wearables-apple-watch-series-9-4.jpg', floor=None, plates=[], keep='all',
        subject='two Apple Watch Series 9'),
    'photo-wear-watch-ultra': dict(src='wearables-apple-watch-ultra-1.jpg', floor=None, plates=[],
        subject='an Apple Watch Ultra 2 with a Trail Loop'),
    'photo-wear-ray-ban-meta': dict(src='wearables-meta-ray-ban-1.jpg', floor=None, plates=[],
        subject='Ray-Ban Meta smart glasses'),
}

MODEL = 'birefnet-general'   # cleaner than isnet-general-use on wheels, mirrors and grilles (checked side by side, 2026-10-02)

def mask_of(src):
    """the model's mask, cached in .render/vehicles; each photograph in its own
    process, since BiRefNet on the CPU does not give its memory back"""
    p = os.path.join(REVIEW, 'mask-' + os.path.splitext(src)[0] + '.png')
    if not os.path.exists(p):
        import subprocess
        subprocess.run([sys.executable, os.path.abspath(__file__), '--mask', os.path.join(WEB, src), p], check=True)
    return np.asarray(Image.open(p).convert('L'), np.float32) / 255

def one_mask(src, out):
    from rembg import new_session, remove
    remove(Image.open(src).convert('RGB'), session=new_session(MODEL), only_mask=True).save(out)

def keep_vehicle(a, every=False):
    """the biggest part of the mask and whatever big part touches it; with
    every, also each separate part at least a tenth its size (a coin's two faces)"""
    fg = (a > 0.5).astype(np.uint8)
    n, lab, st, _ = cv2.connectedComponentsWithStats(fg, connectivity=8)
    if n <= 1: return a
    big = 1 + int(np.argmax(st[1:, cv2.CC_STAT_AREA]))
    keep = (lab == big).astype(np.uint8)
    for i in range(1, n):
        if every and i != big and st[i, cv2.CC_STAT_AREA] > 0.10 * st[big, cv2.CC_STAT_AREA]:
            keep |= (lab == i).astype(np.uint8)
    for i in range(1, n):
        if i != big and st[i, cv2.CC_STAT_AREA] > 0.02 * st[big, cv2.CC_STAT_AREA]:
            near = cv2.dilate(keep, np.ones((9, 9), np.uint8)) & (lab == i).astype(np.uint8)
            if near.any(): keep |= (lab == i).astype(np.uint8)
    keep = cv2.dilate(keep, np.ones((5, 5), np.uint8))
    out = a * keep
    out[out < 0.04] = 0
    return out

def unmix(rgb, a):
    """take the old background's colour out of the soft edge"""
    w = (1 - a)[..., None]
    k = (0, 0)
    num = cv2.GaussianBlur(rgb * w, k, 9)
    den = cv2.GaussianBlur(w, k, 9)
    den = den[..., None] if den.ndim == 2 else den
    bg = num / np.maximum(den, 1e-3)
    a3 = a[..., None]
    col = np.where(a3 > 0.04, (rgb - (1 - a3) * bg) / np.maximum(a3, 0.04), rgb)
    edge = (a3 > 0) & (a3 < 0.98)
    return np.where(edge, np.clip(col, 0, 255), rgb)

def blur_plate(img, box):
    x0, y0, x1, y1 = box
    reg = img.crop(box)
    r = max(6, (x1 - x0) // 9)
    reg = reg.resize((max(1, (x1 - x0) // 14), max(1, (y1 - y0) // 14)), Image.BILINEAR).resize(reg.size, Image.BILINEAR)
    reg = reg.filter(ImageFilter.GaussianBlur(r))
    m = Image.new('L', reg.size, 0); ImageDraw.Draw(m).rounded_rectangle([2, 2, reg.width - 3, reg.height - 3], radius=10, fill=255)
    m = m.filter(ImageFilter.GaussianBlur(4))
    img.paste(reg, box[:2], m)

def cut(rid, s):
    im = Image.open(os.path.join(WEB, s['src'])).convert('RGB')
    for b in s['plates']: blur_plate(im, b)
    a = mask_of(s['src'])
    if s['floor'] is not None: a[s['floor']:] = 0
    for x0, y0, x1, y1 in s.get('erase', []): a[y0:y1, x0:x1] = 0   # a neighbour fused to it
    a = keep_vehicle(a, s.get('keep') == 'all')
    rgb = unmix(np.asarray(im, np.float32), a)
    rgba = Image.fromarray(np.dstack([rgb, a * 255]).astype(np.uint8), 'RGBA')
    if s.get('upright'):                            # turned to stand straight (degrees, anticlockwise)
        rgba = rgba.rotate(s['upright'], resample=Image.BICUBIC, expand=True)
        rgba = rgba.crop(rgba.getbbox())
    return check_cutout(rgba)

def review(rows, path):
    T = 360
    sheet = Image.new('RGB', (2 * (T * 2 + 20), ((len(rows) + 1) // 2) * (T + 40)), 'white'); d = ImageDraw.Draw(sheet)
    for i, (rid, img, fails, warns) in enumerate(rows):
        x, y = (i % 2) * (T * 2 + 20), (i // 2) * (T + 40)
        t = img.copy(); t.thumbnail((T, T))
        for j, bgc in enumerate(((236, 236, 236), (28, 30, 36))):
            tile = Image.new('RGBA', (T, T), bgc + (255,)); tile.alpha_composite(t, ((T - t.width) // 2, (T - t.height) // 2))
            sheet.paste(tile.convert('RGB'), (x + j * T, y))
        d.text((x + 4, y + T + 4), rid + '  ' + ('REFUSED: ' + '; '.join(fails) if fails else 'ok ' + '; '.join(warns)), fill=(170, 20, 20) if fails else (20, 110, 40))
    sheet.save(path, quality=88)

def main():
    web = {a['file']: a for a in json.load(open(os.path.join(WEB, 'ATTRIBUTION.json')))}
    os.makedirs(REVIEW, exist_ok=True)
    rows = []
    only = re.compile(os.environ['ONLY']) if os.environ.get('ONLY') else None
    for rid, s in SPEC.items():
        if only and not only.search(rid): continue
        img, fails, warns = cut(rid, s)
        if s['src'] not in web: fails.append(s['src'] + ' has no credit in assets/bg-web/ATTRIBUTION.json')
        rows.append((rid, img, fails, warns))
        img.save(os.path.join(REVIEW, rid + '.png'))
        print(f"{rid:34s} {img.width}x{img.height}  " + ('REFUSED ' + '; '.join(fails) if fails else 'ok ' + '; '.join(warns)))
    review(rows, os.path.join(REVIEW, '_review.jpg'))
    print('review sheet: ' + os.path.join(REVIEW, '_review.jpg'))
    if not WRITE: print('(dry run; pass --write to land the ones marked ok)'); return
    att_p = os.path.join(CUT, 'ATTRIBUTION.json'); att = json.load(open(att_p))
    n = 0
    for rid, img, fails, _ in rows:
        if fails: continue
        img.save(os.path.join(CUT, rid + '.webp'), 'WEBP', quality=90, method=6)
        w = web[SPEC[rid]['src']]
        att[rid] = dict(license=w['license'], artist=w['artist'], page=w['page'],
                        note='cut from assets/bg-web/' + SPEC[rid]['src'] + ' by scripts/cut_vehicle_photos.py'
                             + ('; licence plate blurred' if SPEC[rid]['plates'] else '') + '. ' + SPEC[rid]['subject'])
        n += 1
    json.dump(att, open(att_p, 'w'), ensure_ascii=False, indent=2)
    print(f'landed {n} in assets/cutouts, credited in assets/cutouts/ATTRIBUTION.json')

if __name__ == '__main__':
    if '--mask' in sys.argv:
        i = sys.argv.index('--mask'); one_mask(sys.argv[i + 1], sys.argv[i + 2])
    else:
        main()
