/* Vendor the 2026-09-22 showcase faces into assets/fonts and write
 * assets/fonts/faces.css.
 *
 * All of these are SIL Open Font License 1.1 (Google Fonts), so they may be
 * self-hosted and embedded in exported images commercially. Only the latin
 * subset is kept (the ads are English and Spanish). Variable families come
 * down as one file covering the whole weight range, which faces.css declares
 * as a range so a weight in between is a real instance, never a faux bold.
 *
 *   node scripts/fetch_fonts.mjs          (network: fonts.googleapis.com, fonts.gstatic.com)
 */
import { writeFileSync, existsSync, statSync, readFileSync } from 'node:fs';
import { FONT_FILES } from '../engine/fonts.mjs';
const DIR = new URL('../assets/fonts/', import.meta.url).pathname;
export const FACES = [
  { family:'Unbounded',                  slug:'unbounded',           w:[500, 900] },
  { family:'Bricolage Grotesque',        slug:'bricolage-grotesque', w:[500, 800] },
  { family:'Sofia Sans Extra Condensed', slug:'sofia-sans-xcond',    w:[500, 900] },
  { family:'Schibsted Grotesk',          slug:'schibsted-grotesk',   w:[400, 900] },
  { family:'Gloock',                     slug:'gloock',              w:[400] },
  { family:'Young Serif',                slug:'young-serif',         w:[400] },
  { family:'Tilt Warp',                  slug:'tilt-warp',           w:[400] },
];
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36';
const css = [];
for (const f of FACES){
  const axis = f.w.length === 2 ? 'wght@' + f.w[0] + '..' + f.w[1] : 'wght@' + f.w[0];
  const url = 'https://fonts.googleapis.com/css2?family=' + f.family.replace(/ /g, '+') + ':' + axis + '&display=swap';
  const txt = await fetch(url, { headers:{ 'user-agent':UA } }).then(r => r.text());
  const m = txt.split('/* latin */')[1];
  const src = m && m.match(/url\((https:[^)]+\.woff2)\)/);
  if (!src) throw new Error('no latin woff2 for ' + f.family + '\n' + txt.slice(0, 300));
  const file = f.slug + (f.w.length === 2 ? '-var' : '-' + f.w[0]) + '.woff2';
  if (!existsSync(DIR + file)){
    const buf = Buffer.from(await fetch(src[1]).then(r => r.arrayBuffer()));
    writeFileSync(DIR + file, buf);
  }
  const range = /unicode-range:([^;]+);/.exec(m);
  css.push(`@font-face{font-family:'${f.family}';src:url('${file}') format('woff2');font-weight:${f.w.join(' ')};font-style:normal;font-display:swap;unicode-range:${range ? range[1].trim() : 'U+0000-00FF'}}`);
  console.log(f.family.padEnd(28) + file.padEnd(34) + (statSync(DIR + file).size / 1024).toFixed(0) + ' KB');
}
/* the owner's approved faces (assets/approved-fonts.json, a review of 151),
   already vendored as static latin woff2 files (engine/fonts.mjs lists them):
   the studio loads them from here, never from a font server. Satoshi is a
   house face, declared in styles.css. */
const APPROVED = JSON.parse(readFileSync(new URL('../assets/approved-fonts.json', import.meta.url), 'utf8')).faces.map(f => f.name);
for (const fam of APPROVED){
  if (fam === 'Satoshi' || FACES.some(f => f.family === fam)) continue;
  const files = FONT_FILES[fam];
  if (!files) throw new Error('approved face not vendored: ' + fam);
  for (const [w, file] of Object.entries(files)){
    if (!existsSync(DIR + file)) throw new Error('missing ' + file);
    css.push(`@font-face{font-family:'${fam}';src:url('${file}') format('woff2');font-weight:${w};font-style:normal;font-display:swap}`);
  }
}
console.log(APPROVED.length + ' approved faces declared');
writeFileSync(DIR + 'faces.css', '/* generated by scripts/fetch_fonts.mjs — OFL 1.1 faces, self-hosted */\n' + css.join('\n') + '\n');
console.log('wrote assets/fonts/faces.css');
